import { Navigate } from "react-router-dom";
import type { ReactElement } from "react";
import Index from "./pages/Index";
import PrivacyPolicy from "./pages/PrivacyPolicy";
import TermsOfService from "./pages/TermsOfService";
import CaseStudies from "./pages/CaseStudies";
import InstagramLeadGenerationCaseStudy from "./pages/case-studies/InstagramLeadGenerationCaseStudy";
import ParisCafeVoiceAgentCaseStudy from "./pages/case-studies/ParisCafeVoiceAgentCaseStudy";
import EcommerceCRMCaseStudy from "./pages/case-studies/EcommerceCRMCaseStudy";
import AiAutomationConsultantSmallBusiness from "./pages/AiAutomationConsultantSmallBusiness";
import WhatDoesAnAiAutomationConsultantDo from "./pages/WhatDoesAnAiAutomationConsultantDo";
import Guides from "./pages/Guides";
import N8nVsZapierSmallBusiness from "./pages/N8nVsZapierSmallBusiness";
import AiAppointmentSetter from "./pages/AiAppointmentSetter";
import AiAppointmentSetterSetup from "./pages/AiAppointmentSetterSetup";
import AiAppointmentSetterSetupVsDiySmallBusiness from "./pages/AiAppointmentSetterSetupVsDiySmallBusiness";
import AiAppointmentSetterCostSmallBusiness from "./pages/AiAppointmentSetterCostSmallBusiness";
import AiAppointmentSetterRoiSmallBusiness from "./pages/AiAppointmentSetterRoiSmallBusiness";
import AiLeadFollowUpForServiceBusinesses from "./pages/AiLeadFollowUpForServiceBusinesses";
import AiLeadFollowUpCostSmallBusiness from "./pages/AiLeadFollowUpCostSmallBusiness";
import AiLeadFollowUpRoiSmallBusiness from "./pages/AiLeadFollowUpRoiSmallBusiness";
import MissedCallTextBackCostSmallBusiness from "./pages/MissedCallTextBackCostSmallBusiness";
import MissedCallTextBackRoiSmallBusiness from "./pages/MissedCallTextBackRoiSmallBusiness";
import AiAutomationConsultantCalgary from "./pages/AiAutomationConsultantCalgary";
import AiAutomationConsultantVancouver from "./pages/AiAutomationConsultantVancouver";
import AiAutomationConsultantToronto from "./pages/AiAutomationConsultantToronto";
import AiAutomationConsultantOttawa from "./pages/AiAutomationConsultantOttawa";
import AiAutomationConsultantOntario from "./pages/AiAutomationConsultantOntario";
import AiAutomationConsultantBritishColumbia from "./pages/AiAutomationConsultantBritishColumbia";
import HireAiAutomationConsultantVsAgency from "./pages/HireAiAutomationConsultantVsAgency";
import HireAiAutomationConsultantVsDiy from "./pages/HireAiAutomationConsultantVsDiy";
import HireAiAutomationConsultantVsInHouse from "./pages/HireAiAutomationConsultantVsInHouse";
import HowToHireAiAutomationConsultant from "./pages/HowToHireAiAutomationConsultant";
import HvacDatabaseReactivation from "./pages/HvacDatabaseReactivation";
import AiAutomationConsultantVsFreelancer from "./pages/AiAutomationConsultantVsFreelancer";
import AiChatbotVsAiVoiceAgentForLeadQualification from "./pages/AiChatbotVsAiVoiceAgentForLeadQualification";
import GoHighLevelVsCustomCrmSmallBusiness from "./pages/GoHighLevelVsCustomCrmSmallBusiness";
import GoHighLevelVsKeapSmallBusiness from "./pages/GoHighLevelVsKeapSmallBusiness";
import GoHighLevelVsPipedriveSmallBusiness from "./pages/GoHighLevelVsPipedriveSmallBusiness";
import GoHighLevelVsActiveCampaignSmallBusiness from "./pages/GoHighLevelVsActiveCampaignSmallBusiness";
import GoHighLevelVsCustomCrmForContractors from "./pages/GoHighLevelVsCustomCrmForContractors";
import GoHighLevelVsJobberForContractors from "./pages/GoHighLevelVsJobberForContractors";
import GoHighLevelAutomationSetup from "./pages/GoHighLevelAutomationSetup";
import GoHighLevelAutomationConsultant from "./pages/GoHighLevelAutomationConsultant";
import GoHighLevelConsultantVsSetupHelp from "./pages/GoHighLevelConsultantVsSetupHelp";
import GoHighLevelAutomationConsultantCostSmallBusiness from "./pages/GoHighLevelAutomationConsultantCostSmallBusiness";
import GoHighLevelSetupCostSmallBusiness from "./pages/GoHighLevelSetupCostSmallBusiness";
import GoHighLevelSetupVsDiySmallBusiness from "./pages/GoHighLevelSetupVsDiySmallBusiness";
import GoHighLevelAccountCleanupService from "./pages/GoHighLevelAccountCleanupService";
import GoHighLevelAccountCleanupVsRebuild from "./pages/GoHighLevelAccountCleanupVsRebuild";
import GoHighLevelAccountAuditChecklist from "./pages/GoHighLevelAccountAuditChecklist";
import GoHighLevelSetupMistakesSmallBusiness from "./pages/GoHighLevelSetupMistakesSmallBusiness";
import GoHighLevelVsHubSpotSmallBusiness from "./pages/GoHighLevelVsHubSpotSmallBusiness";
import AiAutomationConsultantPricingSmallBusiness from "./pages/AiAutomationConsultantPricingSmallBusiness";
import BestAiAutomationForServiceBusinesses from "./pages/BestAiAutomationForServiceBusinesses";
import WhatToAutomateFirstForServiceBusinesses from "./pages/WhatToAutomateFirstForServiceBusinesses";
import AiAutomationForHvacCompanies from "./pages/AiAutomationForHvacCompanies";
import WhatToAutomateFirstForHvacCompanies from "./pages/WhatToAutomateFirstForHvacCompanies";
import HvacLeadFollowUpAutomation from "./pages/HvacLeadFollowUpAutomation";
import HvacMissedCallTextBack from "./pages/HvacMissedCallTextBack";
import AiAppointmentSetterForHvac from "./pages/AiAppointmentSetterForHvac";
import HvacSchedulingAndFollowUpAutomation from "./pages/HvacSchedulingAndFollowUpAutomation";
import DispatchHandoffAutomationForHvacCompanies from "./pages/DispatchHandoffAutomationForHvacCompanies";
import AiPhoneAnsweringForHvacCompanies from "./pages/AiPhoneAnsweringForHvacCompanies";
import MissedCallTextBackVsAiPhoneAnsweringForHvacCompanies from "./pages/MissedCallTextBackVsAiPhoneAnsweringForHvacCompanies";
import MissedCallTextBackVsVoicemailForHvacCompanies from "./pages/MissedCallTextBackVsVoicemailForHvacCompanies";
import AiPhoneAnsweringVsVoicemailForHvacCompanies from "./pages/AiPhoneAnsweringVsVoicemailForHvacCompanies";
import ReviewRequestAutomationForHvacCompanies from "./pages/ReviewRequestAutomationForHvacCompanies";
import MaintenanceReminderAutomationForHvacCompanies from "./pages/MaintenanceReminderAutomationForHvacCompanies";
import QuoteFollowUpAutomationForHvacCompanies from "./pages/QuoteFollowUpAutomationForHvacCompanies";
import AiAppointmentSetterForHomeServiceBusinesses from "./pages/AiAppointmentSetterForHomeServiceBusinesses";
import AiAutomationNoTechTeam from "./pages/AiAutomationNoTechTeam";
import AiVoiceAgentForRestaurants from "./pages/AiVoiceAgentForRestaurants";
import AiAutomationForRestaurants from "./pages/AiAutomationForRestaurants";
import WhatToAutomateFirstForRestaurants from "./pages/WhatToAutomateFirstForRestaurants";
import PrivateEventInquiryFollowUpForRestaurants from "./pages/PrivateEventInquiryFollowUpForRestaurants";
import ReservationConfirmationAndReminderAutomationForRestaurants from "./pages/ReservationConfirmationAndReminderAutomationForRestaurants";
import MissedCallTextBackForRestaurants from "./pages/MissedCallTextBackForRestaurants";
import MissedCallTextBackVsAiVoiceAgentForRestaurants from "./pages/MissedCallTextBackVsAiVoiceAgentForRestaurants";
import MissedCallTextBackVsVoicemailForRestaurants from "./pages/MissedCallTextBackVsVoicemailForRestaurants";
import AfterHoursPhoneAnsweringForRestaurants from "./pages/AfterHoursPhoneAnsweringForRestaurants";
import AfterHoursAiPhoneAnsweringVsVoicemailForRestaurants from "./pages/AfterHoursAiPhoneAnsweringVsVoicemailForRestaurants";
import ReviewRequestAutomationForRestaurants from "./pages/ReviewRequestAutomationForRestaurants";
import AiAutomationConsultantEdmonton from "./pages/AiAutomationConsultantEdmonton";
import AiAutomationConsultantAlberta from "./pages/AiAutomationConsultantAlberta";
import AiAutomationConsultantCanada from "./pages/AiAutomationConsultantCanada";
import AiAutomationForRealEstate from "./pages/AiAutomationForRealEstate";
import RealEstateLeadResponseAndFollowUpAutomation from "./pages/RealEstateLeadResponseAndFollowUpAutomation";
import ShowingCoordinationAutomationForRealEstateTeams from "./pages/ShowingCoordinationAutomationForRealEstateTeams";
import WhatToAutomateFirstForRealEstate from "./pages/WhatToAutomateFirstForRealEstate";
import ClientReactivationAutomationForRealEstateTeams from "./pages/ClientReactivationAutomationForRealEstateTeams";
import CrmCleanupAndRoutingForRealEstateTeams from "./pages/CrmCleanupAndRoutingForRealEstateTeams";
import CrmCleanupVsLeadFollowUpForRealEstateTeams from "./pages/CrmCleanupVsLeadFollowUpForRealEstateTeams";
import MissedCallTextBackForRealEstateAgents from "./pages/MissedCallTextBackForRealEstateAgents";
import AiPhoneAnsweringForRealEstateAgents from "./pages/AiPhoneAnsweringForRealEstateAgents";
import ReviewRequestAutomationForRealEstateAgents from "./pages/ReviewRequestAutomationForRealEstateAgents";
import ReferralRequestAutomationForRealEstateAgents from "./pages/ReferralRequestAutomationForRealEstateAgents";
import MissedCallTextBackVsAiPhoneAnsweringForRealEstateAgents from "./pages/MissedCallTextBackVsAiPhoneAnsweringForRealEstateAgents";
import AiPhoneAnsweringVsVoicemailForRealEstateAgents from "./pages/AiPhoneAnsweringVsVoicemailForRealEstateAgents";
import AiAutomationForMortgageBrokers from "./pages/AiAutomationForMortgageBrokers";
import AiLeadFollowUpForMortgageBrokers from "./pages/AiLeadFollowUpForMortgageBrokers";
import DocumentCollectionAutomationForMortgageBrokers from "./pages/DocumentCollectionAutomationForMortgageBrokers";
import IncompleteApplicationFollowUpForMortgageBrokers from "./pages/IncompleteApplicationFollowUpForMortgageBrokers";
import WhatToAutomateFirstForMortgageBrokers from "./pages/WhatToAutomateFirstForMortgageBrokers";
import AppointmentSchedulingAndReminderAutomationForMortgageBrokers from "./pages/AppointmentSchedulingAndReminderAutomationForMortgageBrokers";
import ReferralRequestAutomationForMortgageBrokers from "./pages/ReferralRequestAutomationForMortgageBrokers";
import ReviewRequestAutomationForMortgageBrokers from "./pages/ReviewRequestAutomationForMortgageBrokers";
import MissedCallTextBackForMortgageBrokers from "./pages/MissedCallTextBackForMortgageBrokers";
import MissedCallTextBackVsVoicemailForMortgageBrokers from "./pages/MissedCallTextBackVsVoicemailForMortgageBrokers";
import AiPhoneAnsweringForMortgageBrokers from "./pages/AiPhoneAnsweringForMortgageBrokers";
import MissedCallTextBackVsAiPhoneAnsweringForMortgageBrokers from "./pages/MissedCallTextBackVsAiPhoneAnsweringForMortgageBrokers";
import AiPhoneAnsweringVsVoicemailForMortgageBrokers from "./pages/AiPhoneAnsweringVsVoicemailForMortgageBrokers";
import AiAutomationForDentalPractices from "./pages/AiAutomationForDentalPractices";
import WhatToAutomateFirstForDentalPractices from "./pages/WhatToAutomateFirstForDentalPractices";
import AiLeadFollowUpForDentalPractices from "./pages/AiLeadFollowUpForDentalPractices";
import RecallAndReactivationAutomationForDentalPractices from "./pages/RecallAndReactivationAutomationForDentalPractices";
import NoShowReductionAutomationForDentalPractices from "./pages/NoShowReductionAutomationForDentalPractices";
import AppointmentSchedulingAndReminderAutomationForDentalPractices from "./pages/AppointmentSchedulingAndReminderAutomationForDentalPractices";
import ReviewRequestAutomationForDentalPractices from "./pages/ReviewRequestAutomationForDentalPractices";
import MissedCallTextBackForDentalPractices from "./pages/MissedCallTextBackForDentalPractices";
import MissedCallTextBackVsVoicemailForDentalPractices from "./pages/MissedCallTextBackVsVoicemailForDentalPractices";
import MissedCallTextBackVsAiPhoneAnsweringForDentalPractices from "./pages/MissedCallTextBackVsAiPhoneAnsweringForDentalPractices";
import MissedCallTextBackVsAiPhoneAnsweringForAccountingFirms from "./pages/MissedCallTextBackVsAiPhoneAnsweringForAccountingFirms";
import AiPhoneAnsweringForDentalPractices from "./pages/AiPhoneAnsweringForDentalPractices";
import AiPhoneAnsweringVsVoicemailForDentalPractices from "./pages/AiPhoneAnsweringVsVoicemailForDentalPractices";
import AiAutomationForLawFirms from "./pages/AiAutomationForLawFirms";
import WhatToAutomateFirstForLawFirms from "./pages/WhatToAutomateFirstForLawFirms";
import AiLeadFollowUpForLawFirms from "./pages/AiLeadFollowUpForLawFirms";
import IntakeAndConflictCheckAutomationForLawFirms from "./pages/IntakeAndConflictCheckAutomationForLawFirms";
import ConsultationSchedulingAndReminderAutomationForLawFirms from "./pages/ConsultationSchedulingAndReminderAutomationForLawFirms";
import NoShowReductionAutomationForLawFirms from "./pages/NoShowReductionAutomationForLawFirms";
import UnretainedConsultFollowUpForLawFirms from "./pages/UnretainedConsultFollowUpForLawFirms";
import CaseStatusUpdateAutomationForLawFirms from "./pages/CaseStatusUpdateAutomationForLawFirms";
import AiPhoneAnsweringForLawFirms from "./pages/AiPhoneAnsweringForLawFirms";
import MissedCallTextBackForLawFirms from "./pages/MissedCallTextBackForLawFirms";
import AiPhoneAnsweringVsVoicemailForLawFirms from "./pages/AiPhoneAnsweringVsVoicemailForLawFirms";
import MissedCallTextBackVsAiPhoneAnsweringForLawFirms from "./pages/MissedCallTextBackVsAiPhoneAnsweringForLawFirms";
import MissedCallTextBackVsVoicemailForLawFirms from "./pages/MissedCallTextBackVsVoicemailForLawFirms";
import ReviewRequestAutomationForLawFirms from "./pages/ReviewRequestAutomationForLawFirms";
import AiAutomationForSolarCompanies from "./pages/AiAutomationForSolarCompanies";
import WhatToAutomateFirstForSolarCompanies from "./pages/WhatToAutomateFirstForSolarCompanies";
import UtilityBillCollectionAutomationForSolarCompanies from "./pages/UtilityBillCollectionAutomationForSolarCompanies";
import AiLeadFollowUpForSolarCompanies from "./pages/AiLeadFollowUpForSolarCompanies";
import AppointmentSchedulingAndReminderAutomationForSolarCompanies from "./pages/AppointmentSchedulingAndReminderAutomationForSolarCompanies";
import AiPhoneAnsweringForSolarCompanies from "./pages/AiPhoneAnsweringForSolarCompanies";
import AiPhoneAnsweringVsVoicemailForSolarCompanies from "./pages/AiPhoneAnsweringVsVoicemailForSolarCompanies";
import MissedCallTextBackForSolarCompanies from "./pages/MissedCallTextBackForSolarCompanies";
import MissedCallTextBackVsVoicemailForSolarCompanies from "./pages/MissedCallTextBackVsVoicemailForSolarCompanies";
import MissedCallTextBackVsAiPhoneAnsweringForSolarCompanies from "./pages/MissedCallTextBackVsAiPhoneAnsweringForSolarCompanies";
import QuoteFollowUpAutomationForSolarCompanies from "./pages/QuoteFollowUpAutomationForSolarCompanies";
import ProjectStatusUpdateAutomationForSolarCompanies from "./pages/ProjectStatusUpdateAutomationForSolarCompanies";
import AiAutomationForAccountingFirms from "./pages/AiAutomationForAccountingFirms";
import DocumentCollectionAutomationForAccountingFirms from "./pages/DocumentCollectionAutomationForAccountingFirms";
import ClientOnboardingAutomationForAccountingFirms from "./pages/ClientOnboardingAutomationForAccountingFirms";
import WhatToAutomateFirstForAccountingFirms from "./pages/WhatToAutomateFirstForAccountingFirms";
import AppointmentSchedulingAndReminderAutomationForAccountingFirms from "./pages/AppointmentSchedulingAndReminderAutomationForAccountingFirms";
import SeasonalClientReactivationForAccountingFirms from "./pages/SeasonalClientReactivationForAccountingFirms";
import AiLeadFollowUpForAccountingFirms from "./pages/AiLeadFollowUpForAccountingFirms";
import AiPhoneAnsweringForAccountingFirms from "./pages/AiPhoneAnsweringForAccountingFirms";
import AiPhoneAnsweringCostForAccountingFirms from "./pages/AiPhoneAnsweringCostForAccountingFirms";
import AiPhoneAnsweringVsVoicemailForAccountingFirms from "./pages/AiPhoneAnsweringVsVoicemailForAccountingFirms";
import MissedCallTextBackVsVoicemailForAccountingFirms from "./pages/MissedCallTextBackVsVoicemailForAccountingFirms";
import ReviewRequestAutomationForAccountingFirms from "./pages/ReviewRequestAutomationForAccountingFirms";
import MissedCallTextBackForAccountingFirms from "./pages/MissedCallTextBackForAccountingFirms";
import AiAutomationForPlumbingCompanies from "./pages/AiAutomationForPlumbingCompanies";
import WhatToAutomateFirstForPlumbingCompanies from "./pages/WhatToAutomateFirstForPlumbingCompanies";
import AiLeadFollowUpForPlumbingCompanies from "./pages/AiLeadFollowUpForPlumbingCompanies";
import EstimateFollowUpAutomationForPlumbingCompanies from "./pages/EstimateFollowUpAutomationForPlumbingCompanies";
import MissedCallTextBackForPlumbingCompanies from "./pages/MissedCallTextBackForPlumbingCompanies";
import MissedCallTextBackVsVoicemailForPlumbingCompanies from "./pages/MissedCallTextBackVsVoicemailForPlumbingCompanies";
import MissedCallTextBackVsAiPhoneAnsweringForPlumbingCompanies from "./pages/MissedCallTextBackVsAiPhoneAnsweringForPlumbingCompanies";
import AiPhoneAnsweringForPlumbingCompanies from "./pages/AiPhoneAnsweringForPlumbingCompanies";
import AiPhoneAnsweringVsVoicemailForPlumbingCompanies from "./pages/AiPhoneAnsweringVsVoicemailForPlumbingCompanies";
import AppointmentSchedulingAndReminderAutomationForPlumbingCompanies from "./pages/AppointmentSchedulingAndReminderAutomationForPlumbingCompanies";
import ReviewRequestAutomationForPlumbingCompanies from "./pages/ReviewRequestAutomationForPlumbingCompanies";
import ClientReactivationAutomationForPlumbingCompanies from "./pages/ClientReactivationAutomationForPlumbingCompanies";
import AiAutomationForElectricalContractors from "./pages/AiAutomationForElectricalContractors";
import WhatToAutomateFirstForElectricalContractors from "./pages/WhatToAutomateFirstForElectricalContractors";
import AiLeadFollowUpForElectricalContractors from "./pages/AiLeadFollowUpForElectricalContractors";
import MissedCallTextBackForElectricalContractors from "./pages/MissedCallTextBackForElectricalContractors";
import MissedCallTextBackVsVoicemailForElectricalContractors from "./pages/MissedCallTextBackVsVoicemailForElectricalContractors";
import MissedCallTextBackVsAiPhoneAnsweringForElectricalContractors from "./pages/MissedCallTextBackVsAiPhoneAnsweringForElectricalContractors";
import AiPhoneAnsweringForElectricalContractors from "./pages/AiPhoneAnsweringForElectricalContractors";
import AiPhoneAnsweringVsVoicemailForElectricalContractors from "./pages/AiPhoneAnsweringVsVoicemailForElectricalContractors";
import EstimateFollowUpAutomationForElectricalContractors from "./pages/EstimateFollowUpAutomationForElectricalContractors";
import ReviewRequestAutomationForElectricalContractors from "./pages/ReviewRequestAutomationForElectricalContractors";
import ClientReactivationAutomationForElectricalContractors from "./pages/ClientReactivationAutomationForElectricalContractors";
import AppointmentSchedulingAndReminderAutomationForElectricalContractors from "./pages/AppointmentSchedulingAndReminderAutomationForElectricalContractors";
import CrmAutomationSetupForContractors from "./pages/CrmAutomationSetupForContractors";
import WhatToAutomateFirstForContractors from "./pages/WhatToAutomateFirstForContractors";
import CrmAutomationSetupCostForContractors from "./pages/CrmAutomationSetupCostForContractors";
import CrmAutomationSetupVsDiyForContractors from "./pages/CrmAutomationSetupVsDiyForContractors";
import ClientOnboardingAutomation from "./pages/ClientOnboardingAutomation";
import IntakeFormsAndDocumentCollectionAutomationForServiceBusinesses from "./pages/IntakeFormsAndDocumentCollectionAutomationForServiceBusinesses";
import AiAutomationRoiGuide from "./pages/AiAutomationRoiGuide";
import AiAutomationRoiCalculator from "./pages/AiAutomationRoiCalculator";
import N8nAutomationExamplesSmallBusiness from "./pages/N8nAutomationExamplesSmallBusiness";
import N8nAutomationConsultant from "./pages/N8nAutomationConsultant";
import N8nAutomationSetupForSmallBusiness from "./pages/N8nAutomationSetupForSmallBusiness";
import HowToHireN8nAutomationConsultant from "./pages/HowToHireN8nAutomationConsultant";
import N8nWorkflowCleanupService from "./pages/N8nWorkflowCleanupService";
import N8nWorkflowCleanupVsRebuild from "./pages/N8nWorkflowCleanupVsRebuild";
import N8nWorkflowAuditChecklist from "./pages/N8nWorkflowAuditChecklist";
import N8nAutomationConsultantCostSmallBusiness from "./pages/N8nAutomationConsultantCostSmallBusiness";
import N8nConsultantVsDiySmallBusiness from "./pages/N8nConsultantVsDiySmallBusiness";
import AiEmailSequenceAutomation from "./pages/AiEmailSequenceAutomation";
import AiAutomationForInsuranceAgencies from "./pages/AiAutomationForInsuranceAgencies";
import WhatToAutomateFirstForInsuranceAgencies from "./pages/WhatToAutomateFirstForInsuranceAgencies";
import AiLeadFollowUpForInsuranceAgencies from "./pages/AiLeadFollowUpForInsuranceAgencies";
import RenewalReminderAutomationForInsuranceAgencies from "./pages/RenewalReminderAutomationForInsuranceAgencies";
import QuoteFollowUpAutomationForInsuranceAgencies from "./pages/QuoteFollowUpAutomationForInsuranceAgencies";
import CrossSellAutomationForInsuranceAgencies from "./pages/CrossSellAutomationForInsuranceAgencies";
import ReviewRequestAutomationForInsuranceAgencies from "./pages/ReviewRequestAutomationForInsuranceAgencies";
import ReferralRequestAutomationForInsuranceAgencies from "./pages/ReferralRequestAutomationForInsuranceAgencies";
import AfterHoursInquiryHandlingForInsuranceAgencies from "./pages/AfterHoursInquiryHandlingForInsuranceAgencies";
import MissedCallTextBackForInsuranceAgencies from "./pages/MissedCallTextBackForInsuranceAgencies";
import MissedCallTextBackVsVoicemailForInsuranceAgencies from "./pages/MissedCallTextBackVsVoicemailForInsuranceAgencies";
import MissedCallTextBackVsAiPhoneAnsweringForInsuranceAgencies from "./pages/MissedCallTextBackVsAiPhoneAnsweringForInsuranceAgencies";
import AiPhoneAnsweringForInsuranceAgencies from "./pages/AiPhoneAnsweringForInsuranceAgencies";
import AiPhoneAnsweringVsVoicemailForInsuranceAgencies from "./pages/AiPhoneAnsweringVsVoicemailForInsuranceAgencies";
import AiAutomationForPropertyManagement from "./pages/AiAutomationForPropertyManagement";
import WhatToAutomateFirstForPropertyManagementCompanies from "./pages/WhatToAutomateFirstForPropertyManagementCompanies";
import LeaseRenewalAutomationForPropertyManagementCompanies from "./pages/LeaseRenewalAutomationForPropertyManagementCompanies";
import ShowingCoordinationAutomationForPropertyManagementCompanies from "./pages/ShowingCoordinationAutomationForPropertyManagementCompanies";
import MaintenanceRequestAutomationForPropertyManagementCompanies from "./pages/MaintenanceRequestAutomationForPropertyManagementCompanies";
import TenantOnboardingAutomationForPropertyManagementCompanies from "./pages/TenantOnboardingAutomationForPropertyManagementCompanies";
import TenantCommunicationAutomationForPropertyManagementCompanies from "./pages/TenantCommunicationAutomationForPropertyManagementCompanies";
import AfterHoursTenantCommunicationForPropertyManagementCompanies from "./pages/AfterHoursTenantCommunicationForPropertyManagementCompanies";
import AfterHoursMaintenanceTriageForPropertyManagementCompanies from "./pages/AfterHoursMaintenanceTriageForPropertyManagementCompanies";
import EmergencyVsRoutineMaintenanceIntakeForPropertyManagementCompanies from "./pages/EmergencyVsRoutineMaintenanceIntakeForPropertyManagementCompanies";
import OwnerReportingAutomationForPropertyManagementCompanies from "./pages/OwnerReportingAutomationForPropertyManagementCompanies";
import AiAutomationEcommerce from "./pages/AiAutomationEcommerce";
import WhatToAutomateFirstForEcommerceBrands from "./pages/WhatToAutomateFirstForEcommerceBrands";
import AiAutomationForAutoPartsEcommerce from "./pages/AiAutomationForAutoPartsEcommerce";
import WhatToAutomateFirstForAutoPartsEcommerce from "./pages/WhatToAutomateFirstForAutoPartsEcommerce";
import CrmAutomationVsManualFollowUpForAutoPartsEcommerce from "./pages/CrmAutomationVsManualFollowUpForAutoPartsEcommerce";
import FitmentInquiryAutomationForAutoPartsEcommerce from "./pages/FitmentInquiryAutomationForAutoPartsEcommerce";
import CustomerInquiryAutomationForAutoPartsEcommerce from "./pages/CustomerInquiryAutomationForAutoPartsEcommerce";
import QuoteFollowUpAutomationForAutoPartsEcommerce from "./pages/QuoteFollowUpAutomationForAutoPartsEcommerce";
import StaleLeadFollowUpForAutoPartsEcommerce from "./pages/StaleLeadFollowUpForAutoPartsEcommerce";
import RepeatPurchaseReactivationAutomationForAutoPartsEcommerce from "./pages/RepeatPurchaseReactivationAutomationForAutoPartsEcommerce";
import EcommerceCrmAutomationWithAiFollowUp from "./pages/EcommerceCrmAutomationWithAiFollowUp";
import EcommerceCrmAutomationVsManualFollowUp from "./pages/EcommerceCrmAutomationVsManualFollowUp";
import RepeatPurchaseReactivationAutomationForEcommerceBrands from "./pages/RepeatPurchaseReactivationAutomationForEcommerceBrands";
import CustomerServiceAutomationForEcommerceBrands from "./pages/CustomerServiceAutomationForEcommerceBrands";
import CustomerServiceAutomationVsManualSupportForEcommerceBrands from "./pages/CustomerServiceAutomationVsManualSupportForEcommerceBrands";
import OrderStatusAndReturnSupportAutomationForEcommerceBrands from "./pages/OrderStatusAndReturnSupportAutomationForEcommerceBrands";
import ReviewRequestAutomationForEcommerceBrands from "./pages/ReviewRequestAutomationForEcommerceBrands";
import AfterHoursLeadCapture from "./pages/AfterHoursLeadCapture";
import MissedCallFollowUp from "./pages/MissedCallFollowUp";
import BookingConfirmationAndReminder from "./pages/BookingConfirmationAndReminder";
import AppointmentSchedulingAndReminderAutomationForServiceBusinesses from "./pages/AppointmentSchedulingAndReminderAutomationForServiceBusinesses";
import AppointmentSchedulingAndReminderAutomationVsAiAppointmentSetterForServiceBusinesses from "./pages/AppointmentSchedulingAndReminderAutomationVsAiAppointmentSetterForServiceBusinesses";
import AiPhoneAnswering from "./pages/AiPhoneAnswering";
import MissedCallTextBackVsAiPhoneAnsweringForServiceBusinesses from "./pages/MissedCallTextBackVsAiPhoneAnsweringForServiceBusinesses";
import AiVoiceAgentForLeadQualification from "./pages/AiVoiceAgentForLeadQualification";
import AiVoiceAgentSetupForLeadQualification from "./pages/AiVoiceAgentSetupForLeadQualification";
import AiVoiceAgentSetupCostSmallBusiness from "./pages/AiVoiceAgentSetupCostSmallBusiness";
import AiVoiceAgentSetupMistakesSmallBusiness from "./pages/AiVoiceAgentSetupMistakesSmallBusiness";
import AiVoiceAgentLaunchChecklistSmallBusiness from "./pages/AiVoiceAgentLaunchChecklistSmallBusiness";
import AiVoiceAgentSetupVsDiySmallBusiness from "./pages/AiVoiceAgentSetupVsDiySmallBusiness";
import AiVoiceAgentCostSmallBusiness from "./pages/AiVoiceAgentCostSmallBusiness";
import AiPhoneAnsweringCostSmallBusiness from "./pages/AiPhoneAnsweringCostSmallBusiness";
import AiPhoneAnsweringSetupSmallBusiness from "./pages/AiPhoneAnsweringSetupSmallBusiness";
import AiPhoneAnsweringRoiSmallBusiness from "./pages/AiPhoneAnsweringRoiSmallBusiness";
import AiPhoneAnsweringSetupVsDiySmallBusiness from "./pages/AiPhoneAnsweringSetupVsDiySmallBusiness";
import AiVoiceAgentRoiForLeadFollowUp from "./pages/AiVoiceAgentRoiForLeadFollowUp";
import InstantLeadResponse from "./pages/InstantLeadResponse";
import ContactFormLeadFollowUpAutomation from "./pages/ContactFormLeadFollowUpAutomation";
import ReviewRequestAutomationForServiceBusinesses from "./pages/ReviewRequestAutomationForServiceBusinesses";
import ReferralRequestAutomationForServiceBusinesses from "./pages/ReferralRequestAutomationForServiceBusinesses";
import ReviewRequestVsReferralRequestForServiceBusinesses from "./pages/ReviewRequestVsReferralRequestForServiceBusinesses";
import MissedCallTextBackForServiceBusinesses from "./pages/MissedCallTextBackForServiceBusinesses";
import EstimateFollowUpAutomationForServiceBusinesses from "./pages/EstimateFollowUpAutomationForServiceBusinesses";
import EstimateFollowUpVsQuoteFollowUpForServiceBusinesses from "./pages/EstimateFollowUpVsQuoteFollowUpForServiceBusinesses";
import QuoteFollowUpAutomationForServiceBusinesses from "./pages/QuoteFollowUpAutomationForServiceBusinesses";
import ContactFormAutoresponderVsFullLeadFollowUp from "./pages/ContactFormAutoresponderVsFullLeadFollowUp";
import QuoteFollowUp from "./pages/QuoteFollowUp";
import ClientReactivation from "./pages/ClientReactivation";
import ClientReactivationAutomationForServiceBusinesses from "./pages/ClientReactivationAutomationForServiceBusinesses";
import ClientReactivationCostSmallBusiness from "./pages/ClientReactivationCostSmallBusiness";
import ClientReactivationRoiSmallBusiness from "./pages/ClientReactivationRoiSmallBusiness";
import NoShowReduction from "./pages/NoShowReduction";
import AiAppointmentSetterVsReceptionist from "./pages/AiAppointmentSetterVsReceptionist";
import AiAppointmentSetterVsVirtualAssistant from "./pages/AiAppointmentSetterVsVirtualAssistant";
import AiVoiceAgentVsVoicemail from "./pages/AiVoiceAgentVsVoicemail";
import AiVoiceAgentVsCallCenter from "./pages/AiVoiceAgentVsCallCenter";
import AiVoiceAgentVsAnsweringServiceForSmallBusiness from "./pages/AiVoiceAgentVsAnsweringServiceForSmallBusiness";
import AiVoiceAgentVsHumanAppointmentSetter from "./pages/AiVoiceAgentVsHumanAppointmentSetter";
import AiVoiceAgentVsManualCallbackForServiceBusinesses from "./pages/AiVoiceAgentVsManualCallbackForServiceBusinesses";
import N8nVsMakeSmallBusiness from "./pages/N8nVsMakeSmallBusiness";
import MakeVsZapierSmallBusiness from "./pages/MakeVsZapierSmallBusiness";
import BuildVsBuyAiAutomation from "./pages/BuildVsBuyAiAutomation";
import VapiVsRetellSmallBusiness from "./pages/VapiVsRetellSmallBusiness";
import RetellVsBlandSmallBusiness from "./pages/RetellVsBlandSmallBusiness";
import AiAutomationForChiropractors from "./pages/AiAutomationForChiropractors";
import WhatToAutomateFirstForChiropractors from "./pages/WhatToAutomateFirstForChiropractors";
import CarePlanRecallAutomationForChiropractors from "./pages/CarePlanRecallAutomationForChiropractors";
import NewPatientIntakeAndSchedulingAutomationForChiropractors from "./pages/NewPatientIntakeAndSchedulingAutomationForChiropractors";
import NoShowReductionAutomationForChiropractors from "./pages/NoShowReductionAutomationForChiropractors";
import AiPhoneAnsweringForChiropractors from "./pages/AiPhoneAnsweringForChiropractors";
import AiPhoneAnsweringVsVoicemailForChiropractors from "./pages/AiPhoneAnsweringVsVoicemailForChiropractors";
import MissedCallTextBackVsAiPhoneAnsweringForChiropractors from "./pages/MissedCallTextBackVsAiPhoneAnsweringForChiropractors";
import MissedCallTextBackVsVoicemailForChiropractors from "./pages/MissedCallTextBackVsVoicemailForChiropractors";
import MissedCallTextBackForChiropractors from "./pages/MissedCallTextBackForChiropractors";
import ReviewRequestAutomationForChiropractors from "./pages/ReviewRequestAutomationForChiropractors";
import AiAutomationForCleaningCompanies from "./pages/AiAutomationForCleaningCompanies";
import WhatToAutomateFirstForCleaningCompanies from "./pages/WhatToAutomateFirstForCleaningCompanies";
import QuoteFollowUpAutomationForCleaningCompanies from "./pages/QuoteFollowUpAutomationForCleaningCompanies";
import MissedCallTextBackForCleaningCompanies from "./pages/MissedCallTextBackForCleaningCompanies";
import MissedCallTextBackVsVoicemailForCleaningCompanies from "./pages/MissedCallTextBackVsVoicemailForCleaningCompanies";
import MissedCallTextBackVsAiPhoneAnsweringForCleaningCompanies from "./pages/MissedCallTextBackVsAiPhoneAnsweringForCleaningCompanies";
import AiPhoneAnsweringForCleaningCompanies from "./pages/AiPhoneAnsweringForCleaningCompanies";
import AiPhoneAnsweringVsVoicemailForCleaningCompanies from "./pages/AiPhoneAnsweringVsVoicemailForCleaningCompanies";
import ClientReactivationAutomationForCleaningCompanies from "./pages/ClientReactivationAutomationForCleaningCompanies";
import ReviewRequestAutomationForCleaningCompanies from "./pages/ReviewRequestAutomationForCleaningCompanies";
import AiLeadFollowUpForCleaningCompanies from "./pages/AiLeadFollowUpForCleaningCompanies";
import RecurringCleaningSchedulingAndReminderAutomationForCleaningCompanies from "./pages/RecurringCleaningSchedulingAndReminderAutomationForCleaningCompanies";
import AiAutomationForMedSpas from "./pages/AiAutomationForMedSpas";
import WhatToAutomateFirstForMedSpas from "./pages/WhatToAutomateFirstForMedSpas";
import MissedCallTextBackForMedSpas from "./pages/MissedCallTextBackForMedSpas";
import MissedCallTextBackVsVoicemailForMedSpas from "./pages/MissedCallTextBackVsVoicemailForMedSpas";
import MissedCallTextBackVsAiPhoneAnsweringForMedSpas from "./pages/MissedCallTextBackVsAiPhoneAnsweringForMedSpas";
import AiPhoneAnsweringForMedSpas from "./pages/AiPhoneAnsweringForMedSpas";
import AiPhoneAnsweringVsVoicemailForMedSpas from "./pages/AiPhoneAnsweringVsVoicemailForMedSpas";
import ConsultationBookingAndReminderAutomationForMedSpas from "./pages/ConsultationBookingAndReminderAutomationForMedSpas";
import NoShowReductionAutomationForMedSpas from "./pages/NoShowReductionAutomationForMedSpas";
import TreatmentRecallAutomationForMedSpas from "./pages/TreatmentRecallAutomationForMedSpas";
import ReviewRequestAutomationForMedSpas from "./pages/ReviewRequestAutomationForMedSpas";
import AiLeadFollowUpForMedSpas from "./pages/AiLeadFollowUpForMedSpas";
import AiAutomationForRoofingCompanies from "./pages/AiAutomationForRoofingCompanies";
import WhatToAutomateFirstForRoofingCompanies from "./pages/WhatToAutomateFirstForRoofingCompanies";
import AiLeadFollowUpForRoofingCompanies from "./pages/AiLeadFollowUpForRoofingCompanies";
import InsuranceClaimFollowUpForRoofingCompanies from "./pages/InsuranceClaimFollowUpForRoofingCompanies";
import ClientReactivationAutomationForRoofingCompanies from "./pages/ClientReactivationAutomationForRoofingCompanies";
import MissedCallTextBackForRoofingCompanies from "./pages/MissedCallTextBackForRoofingCompanies";
import MissedCallTextBackVsAiPhoneAnsweringForRoofingCompanies from "./pages/MissedCallTextBackVsAiPhoneAnsweringForRoofingCompanies";
import MissedCallTextBackVsVoicemailForRoofingCompanies from "./pages/MissedCallTextBackVsVoicemailForRoofingCompanies";
import AiPhoneAnsweringForRoofingCompanies from "./pages/AiPhoneAnsweringForRoofingCompanies";
import AiPhoneAnsweringVsVoicemailForRoofingCompanies from "./pages/AiPhoneAnsweringVsVoicemailForRoofingCompanies";
import ReviewRequestAutomationForRoofingCompanies from "./pages/ReviewRequestAutomationForRoofingCompanies";
import AiAutomationForPestControlCompanies from "./pages/AiAutomationForPestControlCompanies";
import AiAutomationForPoolServiceCompanies from "./pages/AiAutomationForPoolServiceCompanies";
import WhatToAutomateFirstForPoolServiceCompanies from "./pages/WhatToAutomateFirstForPoolServiceCompanies";
import AiLeadFollowUpForPoolServiceCompanies from "./pages/AiLeadFollowUpForPoolServiceCompanies";
import QuoteFollowUpAutomationForPoolServiceCompanies from "./pages/QuoteFollowUpAutomationForPoolServiceCompanies";
import RecurringServiceReminderAutomationForPoolServiceCompanies from "./pages/RecurringServiceReminderAutomationForPoolServiceCompanies";
import SeasonalOpeningAndClosingOutreachForPoolServiceCompanies from "./pages/SeasonalOpeningAndClosingOutreachForPoolServiceCompanies";
import ReviewRequestAutomationForPoolServiceCompanies from "./pages/ReviewRequestAutomationForPoolServiceCompanies";
import MissedCallTextBackForPoolServiceCompanies from "./pages/MissedCallTextBackForPoolServiceCompanies";
import MissedCallTextBackVsVoicemailForPoolServiceCompanies from "./pages/MissedCallTextBackVsVoicemailForPoolServiceCompanies";
import AiPhoneAnsweringForPoolServiceCompanies from "./pages/AiPhoneAnsweringForPoolServiceCompanies";
import AiPhoneAnsweringVsVoicemailForPoolServiceCompanies from "./pages/AiPhoneAnsweringVsVoicemailForPoolServiceCompanies";
import MissedCallTextBackVsAiPhoneAnsweringForPoolServiceCompanies from "./pages/MissedCallTextBackVsAiPhoneAnsweringForPoolServiceCompanies";
import WhatToAutomateFirstForPestControlCompanies from "./pages/WhatToAutomateFirstForPestControlCompanies";
import RecurringServiceReminderAutomationForPestControlCompanies from "./pages/RecurringServiceReminderAutomationForPestControlCompanies";
import SeasonalCampaignAutomationForPestControlCompanies from "./pages/SeasonalCampaignAutomationForPestControlCompanies";
import UrgentLeadFollowUpForPestControlCompanies from "./pages/UrgentLeadFollowUpForPestControlCompanies";
import AiLeadFollowUpForPestControlCompanies from "./pages/AiLeadFollowUpForPestControlCompanies";
import QuoteFollowUpAutomationForPestControlCompanies from "./pages/QuoteFollowUpAutomationForPestControlCompanies";
import ReviewRequestAutomationForPestControlCompanies from "./pages/ReviewRequestAutomationForPestControlCompanies";
import AiPhoneAnsweringForPestControlCompanies from "./pages/AiPhoneAnsweringForPestControlCompanies";
import MissedCallTextBackForPestControlCompanies from "./pages/MissedCallTextBackForPestControlCompanies";
import MissedCallTextBackVsVoicemailForPestControlCompanies from "./pages/MissedCallTextBackVsVoicemailForPestControlCompanies";
import MissedCallTextBackVsAiPhoneAnsweringForPestControlCompanies from "./pages/MissedCallTextBackVsAiPhoneAnsweringForPestControlCompanies";
import AiPhoneAnsweringVsVoicemailForPestControlCompanies from "./pages/AiPhoneAnsweringVsVoicemailForPestControlCompanies";
import AiAutomationForAutoRepairShops from "./pages/AiAutomationForAutoRepairShops";
import WhatToAutomateFirstForAutoRepairShops from "./pages/WhatToAutomateFirstForAutoRepairShops";
import AiLeadFollowUpForAutoRepairShops from "./pages/AiLeadFollowUpForAutoRepairShops";
import MaintenanceReminderAutomationForAutoRepairShops from "./pages/MaintenanceReminderAutomationForAutoRepairShops";
import ClientReactivationAutomationForAutoRepairShops from "./pages/ClientReactivationAutomationForAutoRepairShops";
import EstimateFollowUpAutomationForAutoRepairShops from "./pages/EstimateFollowUpAutomationForAutoRepairShops";
import AppointmentSchedulingAndReminderAutomationForAutoRepairShops from "./pages/AppointmentSchedulingAndReminderAutomationForAutoRepairShops";
import MissedCallTextBackForAutoRepairShops from "./pages/MissedCallTextBackForAutoRepairShops";
import MissedCallTextBackVsVoicemailForAutoRepairShops from "./pages/MissedCallTextBackVsVoicemailForAutoRepairShops";
import MissedCallTextBackVsAiPhoneAnsweringForAutoRepairShops from "./pages/MissedCallTextBackVsAiPhoneAnsweringForAutoRepairShops";
import AiPhoneAnsweringForAutoRepairShops from "./pages/AiPhoneAnsweringForAutoRepairShops";
import AiPhoneAnsweringVsVoicemailForAutoRepairShops from "./pages/AiPhoneAnsweringVsVoicemailForAutoRepairShops";
import ReviewRequestAutomationForAutoRepairShops from "./pages/ReviewRequestAutomationForAutoRepairShops";
import ReviewRequestAutomationForLandscapingCompanies from "./pages/ReviewRequestAutomationForLandscapingCompanies";
import AiAutomationForLandscapingCompanies from "./pages/AiAutomationForLandscapingCompanies";
import WhatToAutomateFirstForLandscapingCompanies from "./pages/WhatToAutomateFirstForLandscapingCompanies";
import AiLeadFollowUpForLandscapingCompanies from "./pages/AiLeadFollowUpForLandscapingCompanies";
import MissedCallTextBackForLandscapingCompanies from "./pages/MissedCallTextBackForLandscapingCompanies";
import MissedCallTextBackVsVoicemailForLandscapingCompanies from "./pages/MissedCallTextBackVsVoicemailForLandscapingCompanies";
import MissedCallTextBackVsAiPhoneAnsweringForLandscapingCompanies from "./pages/MissedCallTextBackVsAiPhoneAnsweringForLandscapingCompanies";
import AiPhoneAnsweringVsVoicemailForLandscapingCompanies from "./pages/AiPhoneAnsweringVsVoicemailForLandscapingCompanies";
import SeasonalReactivationAutomationForLandscapingCompanies from "./pages/SeasonalReactivationAutomationForLandscapingCompanies";
import EstimateFollowUpAutomationForLandscapingCompanies from "./pages/EstimateFollowUpAutomationForLandscapingCompanies";
import RecurringServiceSchedulingAndReminderAutomationForLandscapingCompanies from "./pages/RecurringServiceSchedulingAndReminderAutomationForLandscapingCompanies";
import AiPhoneAnsweringForLandscapingCompanies from "./pages/AiPhoneAnsweringForLandscapingCompanies";
import AiAutomationForPaintingContractors from "./pages/AiAutomationForPaintingContractors";
import AiLeadFollowUpForPaintingContractors from "./pages/AiLeadFollowUpForPaintingContractors";
import ClientReactivationAutomationForPaintingContractors from "./pages/ClientReactivationAutomationForPaintingContractors";
import EstimateFollowUpAutomationForPaintingContractors from "./pages/EstimateFollowUpAutomationForPaintingContractors";
import WhatToAutomateFirstForPaintingContractors from "./pages/WhatToAutomateFirstForPaintingContractors";
import MissedCallTextBackForPaintingContractors from "./pages/MissedCallTextBackForPaintingContractors";
import MissedCallTextBackVsVoicemailForPaintingContractors from "./pages/MissedCallTextBackVsVoicemailForPaintingContractors";
import AiPhoneAnsweringForPaintingContractors from "./pages/AiPhoneAnsweringForPaintingContractors";
import AiPhoneAnsweringVsVoicemailForPaintingContractors from "./pages/AiPhoneAnsweringVsVoicemailForPaintingContractors";
import MissedCallTextBackVsAiPhoneAnsweringForPaintingContractors from "./pages/MissedCallTextBackVsAiPhoneAnsweringForPaintingContractors";
import ReviewRequestAutomationForPaintingContractors from "./pages/ReviewRequestAutomationForPaintingContractors";
import ReferralRequestAutomationForPaintingContractors from "./pages/ReferralRequestAutomationForPaintingContractors";
import AiAutomationForHomeInspectors from "./pages/AiAutomationForHomeInspectors";
import WhatToAutomateFirstForHomeInspectors from "./pages/WhatToAutomateFirstForHomeInspectors";
import AiLeadFollowUpForHomeInspectors from "./pages/AiLeadFollowUpForHomeInspectors";
import InspectionSchedulingAndReminderAutomationForHomeInspectors from "./pages/InspectionSchedulingAndReminderAutomationForHomeInspectors";
import ReportDeliveryAndReviewAutomationForHomeInspectors from "./pages/ReportDeliveryAndReviewAutomationForHomeInspectors";
import ReviewRequestAutomationForHomeInspectors from "./pages/ReviewRequestAutomationForHomeInspectors";
import RealEstateAgentNurtureForHomeInspectors from "./pages/RealEstateAgentNurtureForHomeInspectors";
import AiPhoneAnsweringForHomeInspectors from "./pages/AiPhoneAnsweringForHomeInspectors";
import MissedCallTextBackForHomeInspectors from "./pages/MissedCallTextBackForHomeInspectors";
import MissedCallTextBackVsVoicemailForHomeInspectors from "./pages/MissedCallTextBackVsVoicemailForHomeInspectors";
import MissedCallTextBackVsAiPhoneAnsweringForHomeInspectors from "./pages/MissedCallTextBackVsAiPhoneAnsweringForHomeInspectors";
import AiPhoneAnsweringVsVoicemailForHomeInspectors from "./pages/AiPhoneAnsweringVsVoicemailForHomeInspectors";
import AiAutomationCostSmallBusiness from "./pages/AiAutomationCostSmallBusiness";
import AiAutomationTimeSavingsSmallBusiness from "./pages/AiAutomationTimeSavingsSmallBusiness";
import AiAutomationMaintenanceAndSupportSmallBusiness from "./pages/AiAutomationMaintenanceAndSupportSmallBusiness";
import AffordableAiAutomationSmallBusiness from "./pages/AffordableAiAutomationSmallBusiness";
import AiAutomationAuditChecklist from "./pages/AiAutomationAuditChecklist";
import CrmAutomationExamplesSmallBusiness from "./pages/CrmAutomationExamplesSmallBusiness";
import CrmAutomationForContractors from "./pages/CrmAutomationForContractors";
import CrmPipelineStagesForContractors from "./pages/CrmPipelineStagesForContractors";
import EstimateFollowUpAutomationForContractors from "./pages/EstimateFollowUpAutomationForContractors";
import EstimateFollowUpAutomationForRoofingCompanies from "./pages/EstimateFollowUpAutomationForRoofingCompanies";
import RoofingSchedulingAndFollowUpAutomation from "./pages/RoofingSchedulingAndFollowUpAutomation";
import DispatchHandoffAutomationForContractors from "./pages/DispatchHandoffAutomationForContractors";
import JobIntakeRoutingAutomationForContractors from "./pages/JobIntakeRoutingAutomationForContractors";
import LeadFollowUpAutomationExamples from "./pages/LeadFollowUpAutomationExamples";
import AiAutomationImplementationRoadmap from "./pages/AiAutomationImplementationRoadmap";
import AiAutomationIntegrationsSmallBusiness from "./pages/AiAutomationIntegrationsSmallBusiness";
import WhatProcessesCanAiAutomateInMyBusiness from "./pages/WhatProcessesCanAiAutomateInMyBusiness";
import NotFound from "./pages/NotFound";

export type AppRouteDefinition = {
  path: string;
  element: ReactElement;
  prerender?: boolean;
};

export const appRoutes: AppRouteDefinition[] = [
  { path: "/", element: <Index /> },
  { path: "/case-studies", element: <CaseStudies /> },
  { path: "/case-studies/instagram-lead-generation", element: <InstagramLeadGenerationCaseStudy /> },
  { path: "/case-studies/paris-cafe-voice-agent", element: <ParisCafeVoiceAgentCaseStudy /> },
  { path: "/case-studies/ecommerce-crm-automation", element: <EcommerceCRMCaseStudy /> },
  { path: "/ai-automation-consultant-small-business", element: <AiAutomationConsultantSmallBusiness /> },
  { path: "/what-does-an-ai-automation-consultant-do", element: <WhatDoesAnAiAutomationConsultantDo /> },
  { path: "/guides", element: <Guides /> },
  { path: "/n8n-vs-zapier-small-business", element: <N8nVsZapierSmallBusiness /> },
  { path: "/ai-appointment-setter", element: <AiAppointmentSetter /> },
  { path: "/ai-appointment-setter-setup", element: <AiAppointmentSetterSetup /> },
  { path: "/ai-appointment-setter-setup-vs-diy-small-business", element: <AiAppointmentSetterSetupVsDiySmallBusiness /> },
  { path: "/ai-appointment-setter-cost-small-business", element: <AiAppointmentSetterCostSmallBusiness /> },
  { path: "/ai-appointment-setter-roi-small-business", element: <AiAppointmentSetterRoiSmallBusiness /> },
  { path: "/ai-lead-follow-up-for-service-businesses", element: <AiLeadFollowUpForServiceBusinesses /> },
  { path: "/ai-lead-follow-up-cost-small-business", element: <AiLeadFollowUpCostSmallBusiness /> },
  { path: "/ai-lead-follow-up-roi-small-business", element: <AiLeadFollowUpRoiSmallBusiness /> },
  { path: "/missed-call-text-back-cost-small-business", element: <MissedCallTextBackCostSmallBusiness /> },
  { path: "/missed-call-text-back-roi-small-business", element: <MissedCallTextBackRoiSmallBusiness /> },
  { path: "/ai-automation-consultant-calgary", element: <AiAutomationConsultantCalgary /> },
  { path: "/ai-automation-consultant-edmonton", element: <AiAutomationConsultantEdmonton /> },
  { path: "/ai-automation-consultant-vancouver", element: <AiAutomationConsultantVancouver /> },
  { path: "/ai-automation-consultant-toronto", element: <AiAutomationConsultantToronto /> },
  { path: "/ai-automation-consultant-ottawa", element: <AiAutomationConsultantOttawa /> },
  { path: "/ai-automation-consultant-ontario", element: <AiAutomationConsultantOntario /> },
  { path: "/ai-automation-consultant-british-columbia", element: <AiAutomationConsultantBritishColumbia /> },
  {
    path: "/ai-automation-hvac",
    element: <Navigate to="/ai-automation-for-hvac-companies" replace />,
    prerender: false,
  },
  { path: "/hire-ai-automation-consultant-vs-agency", element: <HireAiAutomationConsultantVsAgency /> },
  { path: "/hire-ai-automation-consultant-vs-diy", element: <HireAiAutomationConsultantVsDiy /> },
  { path: "/hire-ai-automation-consultant-vs-in-house", element: <HireAiAutomationConsultantVsInHouse /> },
  { path: "/how-to-hire-ai-automation-consultant", element: <HowToHireAiAutomationConsultant /> },
  { path: "/hvac-database-reactivation", element: <HvacDatabaseReactivation /> },
  { path: "/ai-automation-consultant-vs-freelancer", element: <AiAutomationConsultantVsFreelancer /> },
  {
    path: "/ai-chatbot-vs-ai-voice-agent-for-lead-qualification",
    element: <AiChatbotVsAiVoiceAgentForLeadQualification />,
  },
  { path: "/gohighlevel-vs-custom-crm-small-business", element: <GoHighLevelVsCustomCrmSmallBusiness /> },
  { path: "/gohighlevel-vs-keap-small-business", element: <GoHighLevelVsKeapSmallBusiness /> },
  { path: "/gohighlevel-vs-pipedrive-small-business", element: <GoHighLevelVsPipedriveSmallBusiness /> },
  { path: "/gohighlevel-vs-activecampaign-small-business", element: <GoHighLevelVsActiveCampaignSmallBusiness /> },
  { path: "/gohighlevel-vs-custom-crm-for-contractors", element: <GoHighLevelVsCustomCrmForContractors /> },
  { path: "/gohighlevel-vs-jobber-for-contractors", element: <GoHighLevelVsJobberForContractors /> },
  { path: "/gohighlevel-automation-setup", element: <GoHighLevelAutomationSetup /> },
  { path: "/gohighlevel-automation-consultant", element: <GoHighLevelAutomationConsultant /> },
  { path: "/gohighlevel-consultant-vs-setup-help", element: <GoHighLevelConsultantVsSetupHelp /> },
  { path: "/gohighlevel-automation-consultant-cost-small-business", element: <GoHighLevelAutomationConsultantCostSmallBusiness /> },
  { path: "/gohighlevel-setup-cost-small-business", element: <GoHighLevelSetupCostSmallBusiness /> },
  { path: "/gohighlevel-setup-vs-diy-small-business", element: <GoHighLevelSetupVsDiySmallBusiness /> },
  { path: "/gohighlevel-account-cleanup-service", element: <GoHighLevelAccountCleanupService /> },
  { path: "/gohighlevel-account-cleanup-vs-rebuild", element: <GoHighLevelAccountCleanupVsRebuild /> },
  { path: "/gohighlevel-account-audit-checklist", element: <GoHighLevelAccountAuditChecklist /> },
  { path: "/gohighlevel-setup-mistakes-small-business", element: <GoHighLevelSetupMistakesSmallBusiness /> },
  { path: "/gohighlevel-vs-hubspot-small-business", element: <GoHighLevelVsHubSpotSmallBusiness /> },
  {
    path: "/ai-automation-consultant-pricing-small-business",
    element: <AiAutomationConsultantPricingSmallBusiness />,
  },
  { path: "/best-ai-automation-for-service-businesses", element: <BestAiAutomationForServiceBusinesses /> },
  { path: "/what-to-automate-first-for-service-businesses", element: <WhatToAutomateFirstForServiceBusinesses /> },
  { path: "/ai-automation-for-hvac-companies", element: <AiAutomationForHvacCompanies /> },
  { path: "/what-to-automate-first-for-hvac-companies", element: <WhatToAutomateFirstForHvacCompanies /> },
  { path: "/hvac-lead-follow-up-automation", element: <HvacLeadFollowUpAutomation /> },
  { path: "/hvac-missed-call-text-back", element: <HvacMissedCallTextBack /> },
  { path: "/ai-appointment-setter-for-hvac", element: <AiAppointmentSetterForHvac /> },
  { path: "/hvac-scheduling-and-follow-up-automation", element: <HvacSchedulingAndFollowUpAutomation /> },
  { path: "/dispatch-handoff-automation-for-hvac-companies", element: <DispatchHandoffAutomationForHvacCompanies /> },
  { path: "/ai-phone-answering-for-hvac-companies", element: <AiPhoneAnsweringForHvacCompanies /> },
  { path: "/missed-call-text-back-vs-ai-phone-answering-for-hvac-companies", element: <MissedCallTextBackVsAiPhoneAnsweringForHvacCompanies /> },
  { path: "/missed-call-text-back-vs-voicemail-for-hvac-companies", element: <MissedCallTextBackVsVoicemailForHvacCompanies /> },
  { path: "/ai-phone-answering-vs-voicemail-for-hvac-companies", element: <AiPhoneAnsweringVsVoicemailForHvacCompanies /> },
  { path: "/review-request-automation-for-hvac-companies", element: <ReviewRequestAutomationForHvacCompanies /> },
  { path: "/maintenance-reminder-automation-for-hvac-companies", element: <MaintenanceReminderAutomationForHvacCompanies /> },
  { path: "/quote-follow-up-automation-for-hvac-companies", element: <QuoteFollowUpAutomationForHvacCompanies /> },
  { path: "/ai-appointment-setter-for-home-service-businesses", element: <AiAppointmentSetterForHomeServiceBusinesses /> },
  { path: "/ai-automation-for-businesses-without-a-tech-team", element: <AiAutomationNoTechTeam /> },
  { path: "/ai-voice-agent-for-restaurants", element: <AiVoiceAgentForRestaurants /> },
  { path: "/ai-automation-for-restaurants", element: <AiAutomationForRestaurants /> },
  { path: "/what-to-automate-first-for-restaurants", element: <WhatToAutomateFirstForRestaurants /> },
  { path: "/private-event-inquiry-follow-up-for-restaurants", element: <PrivateEventInquiryFollowUpForRestaurants /> },
  { path: "/reservation-confirmation-and-reminder-automation-for-restaurants", element: <ReservationConfirmationAndReminderAutomationForRestaurants /> },
  { path: "/missed-call-text-back-for-restaurants", element: <MissedCallTextBackForRestaurants /> },
  {
    path: "/missed-call-text-back-vs-ai-voice-agent-for-restaurants",
    element: <MissedCallTextBackVsAiVoiceAgentForRestaurants />,
  },
  {
    path: "/missed-call-text-back-vs-voicemail-for-restaurants",
    element: <MissedCallTextBackVsVoicemailForRestaurants />,
  },
  { path: "/after-hours-phone-answering-for-restaurants", element: <AfterHoursPhoneAnsweringForRestaurants /> },
  { path: "/after-hours-ai-phone-answering-vs-voicemail-for-restaurants", element: <AfterHoursAiPhoneAnsweringVsVoicemailForRestaurants /> },
  { path: "/review-request-automation-for-restaurants", element: <ReviewRequestAutomationForRestaurants /> },
  { path: "/ai-automation-consultant-alberta", element: <AiAutomationConsultantAlberta /> },
  { path: "/ai-automation-consultant-canada", element: <AiAutomationConsultantCanada /> },
  { path: "/ai-automation-for-real-estate", element: <AiAutomationForRealEstate /> },
  {
    path: "/real-estate-lead-response-and-follow-up-automation",
    element: <RealEstateLeadResponseAndFollowUpAutomation />,
  },
  {
    path: "/showing-coordination-automation-for-real-estate-teams",
    element: <ShowingCoordinationAutomationForRealEstateTeams />,
  },
  { path: "/what-to-automate-first-for-real-estate", element: <WhatToAutomateFirstForRealEstate /> },
  {
    path: "/client-reactivation-automation-for-real-estate-teams",
    element: <ClientReactivationAutomationForRealEstateTeams />,
  },
  {
    path: "/crm-cleanup-and-routing-for-real-estate-teams",
    element: <CrmCleanupAndRoutingForRealEstateTeams />,
  },
  {
    path: "/crm-cleanup-vs-lead-follow-up-for-real-estate-teams",
    element: <CrmCleanupVsLeadFollowUpForRealEstateTeams />,
  },
  { path: "/missed-call-text-back-for-real-estate-agents", element: <MissedCallTextBackForRealEstateAgents /> },
  { path: "/ai-phone-answering-for-real-estate-agents", element: <AiPhoneAnsweringForRealEstateAgents /> },
  { path: "/review-request-automation-for-real-estate-agents", element: <ReviewRequestAutomationForRealEstateAgents /> },
  { path: "/referral-request-automation-for-real-estate-agents", element: <ReferralRequestAutomationForRealEstateAgents /> },
  { path: "/missed-call-text-back-vs-ai-phone-answering-for-real-estate-agents", element: <MissedCallTextBackVsAiPhoneAnsweringForRealEstateAgents /> },
  { path: "/ai-phone-answering-vs-voicemail-for-real-estate-agents", element: <AiPhoneAnsweringVsVoicemailForRealEstateAgents /> },
  { path: "/ai-automation-for-mortgage-brokers", element: <AiAutomationForMortgageBrokers /> },
  { path: "/ai-lead-follow-up-for-mortgage-brokers", element: <AiLeadFollowUpForMortgageBrokers /> },
  { path: "/document-collection-automation-for-mortgage-brokers", element: <DocumentCollectionAutomationForMortgageBrokers /> },
  { path: "/incomplete-application-follow-up-for-mortgage-brokers", element: <IncompleteApplicationFollowUpForMortgageBrokers /> },
  { path: "/what-to-automate-first-for-mortgage-brokers", element: <WhatToAutomateFirstForMortgageBrokers /> },
  { path: "/appointment-scheduling-and-reminder-automation-for-mortgage-brokers", element: <AppointmentSchedulingAndReminderAutomationForMortgageBrokers /> },
  { path: "/referral-request-automation-for-mortgage-brokers", element: <ReferralRequestAutomationForMortgageBrokers /> },
  { path: "/review-request-automation-for-mortgage-brokers", element: <ReviewRequestAutomationForMortgageBrokers /> },
  { path: "/missed-call-text-back-for-mortgage-brokers", element: <MissedCallTextBackForMortgageBrokers /> },
  { path: "/missed-call-text-back-vs-voicemail-for-mortgage-brokers", element: <MissedCallTextBackVsVoicemailForMortgageBrokers /> },
  { path: "/ai-phone-answering-for-mortgage-brokers", element: <AiPhoneAnsweringForMortgageBrokers /> },
  { path: "/missed-call-text-back-vs-ai-phone-answering-for-mortgage-brokers", element: <MissedCallTextBackVsAiPhoneAnsweringForMortgageBrokers /> },
  { path: "/ai-phone-answering-vs-voicemail-for-mortgage-brokers", element: <AiPhoneAnsweringVsVoicemailForMortgageBrokers /> },
  { path: "/ai-automation-for-dental-practices", element: <AiAutomationForDentalPractices /> },
  { path: "/what-to-automate-first-for-dental-practices", element: <WhatToAutomateFirstForDentalPractices /> },
  { path: "/ai-lead-follow-up-for-dental-practices", element: <AiLeadFollowUpForDentalPractices /> },
  { path: "/appointment-scheduling-and-reminder-automation-for-dental-practices", element: <AppointmentSchedulingAndReminderAutomationForDentalPractices /> },
  { path: "/recall-and-reactivation-automation-for-dental-practices", element: <RecallAndReactivationAutomationForDentalPractices /> },
  { path: "/no-show-reduction-automation-for-dental-practices", element: <NoShowReductionAutomationForDentalPractices /> },
  { path: "/review-request-automation-for-dental-practices", element: <ReviewRequestAutomationForDentalPractices /> },
  { path: "/missed-call-text-back-for-dental-practices", element: <MissedCallTextBackForDentalPractices /> },
  { path: "/missed-call-text-back-vs-voicemail-for-dental-practices", element: <MissedCallTextBackVsVoicemailForDentalPractices /> },
  { path: "/missed-call-text-back-vs-ai-phone-answering-for-dental-practices", element: <MissedCallTextBackVsAiPhoneAnsweringForDentalPractices /> },
  { path: "/ai-phone-answering-for-dental-practices", element: <AiPhoneAnsweringForDentalPractices /> },
  { path: "/ai-phone-answering-vs-voicemail-for-dental-practices", element: <AiPhoneAnsweringVsVoicemailForDentalPractices /> },
  { path: "/ai-automation-for-law-firms", element: <AiAutomationForLawFirms /> },
  { path: "/what-to-automate-first-for-law-firms", element: <WhatToAutomateFirstForLawFirms /> },
  { path: "/ai-lead-follow-up-for-law-firms", element: <AiLeadFollowUpForLawFirms /> },
  { path: "/intake-and-conflict-check-automation-for-law-firms", element: <IntakeAndConflictCheckAutomationForLawFirms /> },
  { path: "/consultation-scheduling-and-reminder-automation-for-law-firms", element: <ConsultationSchedulingAndReminderAutomationForLawFirms /> },
  { path: "/no-show-reduction-automation-for-law-firms", element: <NoShowReductionAutomationForLawFirms /> },
  { path: "/unretained-consult-follow-up-for-law-firms", element: <UnretainedConsultFollowUpForLawFirms /> },
  { path: "/case-status-update-automation-for-law-firms", element: <CaseStatusUpdateAutomationForLawFirms /> },
  { path: "/ai-phone-answering-for-law-firms", element: <AiPhoneAnsweringForLawFirms /> },
  { path: "/missed-call-text-back-for-law-firms", element: <MissedCallTextBackForLawFirms /> },
  { path: "/ai-phone-answering-vs-voicemail-for-law-firms", element: <AiPhoneAnsweringVsVoicemailForLawFirms /> },
  { path: "/missed-call-text-back-vs-ai-phone-answering-for-law-firms", element: <MissedCallTextBackVsAiPhoneAnsweringForLawFirms /> },
  { path: "/missed-call-text-back-vs-voicemail-for-law-firms", element: <MissedCallTextBackVsVoicemailForLawFirms /> },
  { path: "/review-request-automation-for-law-firms", element: <ReviewRequestAutomationForLawFirms /> },
  { path: "/ai-automation-for-solar-companies", element: <AiAutomationForSolarCompanies /> },
  { path: "/what-to-automate-first-for-solar-companies", element: <WhatToAutomateFirstForSolarCompanies /> },
  { path: "/utility-bill-collection-automation-for-solar-companies", element: <UtilityBillCollectionAutomationForSolarCompanies /> },
  { path: "/ai-lead-follow-up-for-solar-companies", element: <AiLeadFollowUpForSolarCompanies /> },
  { path: "/quote-follow-up-automation-for-solar-companies", element: <QuoteFollowUpAutomationForSolarCompanies /> },
  { path: "/project-status-update-automation-for-solar-companies", element: <ProjectStatusUpdateAutomationForSolarCompanies /> },
  { path: "/appointment-scheduling-and-reminder-automation-for-solar-companies", element: <AppointmentSchedulingAndReminderAutomationForSolarCompanies /> },
  { path: "/ai-phone-answering-for-solar-companies", element: <AiPhoneAnsweringForSolarCompanies /> },
  { path: "/ai-phone-answering-vs-voicemail-for-solar-companies", element: <AiPhoneAnsweringVsVoicemailForSolarCompanies /> },
  { path: "/missed-call-text-back-for-solar-companies", element: <MissedCallTextBackForSolarCompanies /> },
  { path: "/missed-call-text-back-vs-voicemail-for-solar-companies", element: <MissedCallTextBackVsVoicemailForSolarCompanies /> },
  { path: "/missed-call-text-back-vs-ai-phone-answering-for-solar-companies", element: <MissedCallTextBackVsAiPhoneAnsweringForSolarCompanies /> },
  { path: "/ai-automation-for-accounting-firms", element: <AiAutomationForAccountingFirms /> },
  { path: "/document-collection-automation-for-accounting-firms", element: <DocumentCollectionAutomationForAccountingFirms /> },
  { path: "/client-onboarding-automation-for-accounting-firms", element: <ClientOnboardingAutomationForAccountingFirms /> },
  { path: "/what-to-automate-first-for-accounting-firms", element: <WhatToAutomateFirstForAccountingFirms /> },
  { path: "/appointment-scheduling-and-reminder-automation-for-accounting-firms", element: <AppointmentSchedulingAndReminderAutomationForAccountingFirms /> },
  { path: "/seasonal-client-reactivation-for-accounting-firms", element: <SeasonalClientReactivationForAccountingFirms /> },
  { path: "/ai-lead-follow-up-for-accounting-firms", element: <AiLeadFollowUpForAccountingFirms /> },
  { path: "/ai-phone-answering-for-accounting-firms", element: <AiPhoneAnsweringForAccountingFirms /> },
  { path: "/ai-phone-answering-cost-for-accounting-firms", element: <AiPhoneAnsweringCostForAccountingFirms /> },
  { path: "/ai-phone-answering-vs-voicemail-for-accounting-firms", element: <AiPhoneAnsweringVsVoicemailForAccountingFirms /> },
  { path: "/missed-call-text-back-vs-ai-phone-answering-for-accounting-firms", element: <MissedCallTextBackVsAiPhoneAnsweringForAccountingFirms /> },
  { path: "/missed-call-text-back-vs-voicemail-for-accounting-firms", element: <MissedCallTextBackVsVoicemailForAccountingFirms /> },
  { path: "/missed-call-text-back-for-accounting-firms", element: <MissedCallTextBackForAccountingFirms /> },
  { path: "/review-request-automation-for-accounting-firms", element: <ReviewRequestAutomationForAccountingFirms /> },
  { path: "/ai-automation-for-plumbing-companies", element: <AiAutomationForPlumbingCompanies /> },
  { path: "/what-to-automate-first-for-plumbing-companies", element: <WhatToAutomateFirstForPlumbingCompanies /> },
  { path: "/ai-lead-follow-up-for-plumbing-companies", element: <AiLeadFollowUpForPlumbingCompanies /> },
  { path: "/estimate-follow-up-automation-for-plumbing-companies", element: <EstimateFollowUpAutomationForPlumbingCompanies /> },
  { path: "/missed-call-text-back-for-plumbing-companies", element: <MissedCallTextBackForPlumbingCompanies /> },
  { path: "/missed-call-text-back-vs-voicemail-for-plumbing-companies", element: <MissedCallTextBackVsVoicemailForPlumbingCompanies /> },
  { path: "/missed-call-text-back-vs-ai-phone-answering-for-plumbing-companies", element: <MissedCallTextBackVsAiPhoneAnsweringForPlumbingCompanies /> },
  { path: "/ai-phone-answering-for-plumbing-companies", element: <AiPhoneAnsweringForPlumbingCompanies /> },
  { path: "/ai-phone-answering-vs-voicemail-for-plumbing-companies", element: <AiPhoneAnsweringVsVoicemailForPlumbingCompanies /> },
  { path: "/appointment-scheduling-and-reminder-automation-for-plumbing-companies", element: <AppointmentSchedulingAndReminderAutomationForPlumbingCompanies /> },
  { path: "/review-request-automation-for-plumbing-companies", element: <ReviewRequestAutomationForPlumbingCompanies /> },
  { path: "/client-reactivation-automation-for-plumbing-companies", element: <ClientReactivationAutomationForPlumbingCompanies /> },
  { path: "/ai-automation-for-electrical-contractors", element: <AiAutomationForElectricalContractors /> },
  { path: "/what-to-automate-first-for-electrical-contractors", element: <WhatToAutomateFirstForElectricalContractors /> },
  { path: "/ai-lead-follow-up-for-electrical-contractors", element: <AiLeadFollowUpForElectricalContractors /> },
  { path: "/missed-call-text-back-for-electrical-contractors", element: <MissedCallTextBackForElectricalContractors /> },
  { path: "/missed-call-text-back-vs-voicemail-for-electrical-contractors", element: <MissedCallTextBackVsVoicemailForElectricalContractors /> },
  { path: "/missed-call-text-back-vs-ai-phone-answering-for-electrical-contractors", element: <MissedCallTextBackVsAiPhoneAnsweringForElectricalContractors /> },
  { path: "/ai-phone-answering-for-electrical-contractors", element: <AiPhoneAnsweringForElectricalContractors /> },
  { path: "/ai-phone-answering-vs-voicemail-for-electrical-contractors", element: <AiPhoneAnsweringVsVoicemailForElectricalContractors /> },
  { path: "/appointment-scheduling-and-reminder-automation-for-electrical-contractors", element: <AppointmentSchedulingAndReminderAutomationForElectricalContractors /> },
  { path: "/estimate-follow-up-automation-for-electrical-contractors", element: <EstimateFollowUpAutomationForElectricalContractors /> },
  { path: "/review-request-automation-for-electrical-contractors", element: <ReviewRequestAutomationForElectricalContractors /> },
  { path: "/client-reactivation-automation-for-electrical-contractors", element: <ClientReactivationAutomationForElectricalContractors /> },
  { path: "/client-onboarding-automation", element: <ClientOnboardingAutomation /> },
  {
    path: "/intake-forms-and-document-collection-automation-for-service-businesses",
    element: <IntakeFormsAndDocumentCollectionAutomationForServiceBusinesses />,
  },
  { path: "/ai-automation-roi-guide", element: <AiAutomationRoiGuide /> },
  { path: "/ai-automation-roi-calculator", element: <AiAutomationRoiCalculator /> },
  { path: "/n8n-automation-examples-small-business", element: <N8nAutomationExamplesSmallBusiness /> },
  { path: "/n8n-automation-consultant", element: <N8nAutomationConsultant /> },
  { path: "/n8n-automation-setup-for-small-business", element: <N8nAutomationSetupForSmallBusiness /> },
  { path: "/how-to-hire-n8n-automation-consultant", element: <HowToHireN8nAutomationConsultant /> },
  { path: "/n8n-workflow-cleanup-service", element: <N8nWorkflowCleanupService /> },
  { path: "/n8n-workflow-cleanup-vs-rebuild", element: <N8nWorkflowCleanupVsRebuild /> },
  { path: "/n8n-workflow-audit-checklist", element: <N8nWorkflowAuditChecklist /> },
  { path: "/n8n-automation-consultant-cost-small-business", element: <N8nAutomationConsultantCostSmallBusiness /> },
  { path: "/n8n-consultant-vs-diy-small-business", element: <N8nConsultantVsDiySmallBusiness /> },
  { path: "/ai-email-sequence-automation", element: <AiEmailSequenceAutomation /> },
  { path: "/ai-automation-for-insurance-agencies", element: <AiAutomationForInsuranceAgencies /> },
  { path: "/what-to-automate-first-for-insurance-agencies", element: <WhatToAutomateFirstForInsuranceAgencies /> },
  { path: "/ai-lead-follow-up-for-insurance-agencies", element: <AiLeadFollowUpForInsuranceAgencies /> },
  { path: "/renewal-reminder-automation-for-insurance-agencies", element: <RenewalReminderAutomationForInsuranceAgencies /> },
  { path: "/quote-follow-up-automation-for-insurance-agencies", element: <QuoteFollowUpAutomationForInsuranceAgencies /> },
  { path: "/cross-sell-automation-for-insurance-agencies", element: <CrossSellAutomationForInsuranceAgencies /> },
  { path: "/review-request-automation-for-insurance-agencies", element: <ReviewRequestAutomationForInsuranceAgencies /> },
  { path: "/referral-request-automation-for-insurance-agencies", element: <ReferralRequestAutomationForInsuranceAgencies /> },
  { path: "/after-hours-inquiry-handling-for-insurance-agencies", element: <AfterHoursInquiryHandlingForInsuranceAgencies /> },
  { path: "/missed-call-text-back-for-insurance-agencies", element: <MissedCallTextBackForInsuranceAgencies /> },
  { path: "/missed-call-text-back-vs-voicemail-for-insurance-agencies", element: <MissedCallTextBackVsVoicemailForInsuranceAgencies /> },
  { path: "/missed-call-text-back-vs-ai-phone-answering-for-insurance-agencies", element: <MissedCallTextBackVsAiPhoneAnsweringForInsuranceAgencies /> },
  { path: "/ai-phone-answering-for-insurance-agencies", element: <AiPhoneAnsweringForInsuranceAgencies /> },
  { path: "/ai-phone-answering-vs-voicemail-for-insurance-agencies", element: <AiPhoneAnsweringVsVoicemailForInsuranceAgencies /> },
  { path: "/ai-automation-for-property-management", element: <AiAutomationForPropertyManagement /> },
  { path: "/what-to-automate-first-for-property-management-companies", element: <WhatToAutomateFirstForPropertyManagementCompanies /> },
  { path: "/lease-renewal-automation-for-property-management-companies", element: <LeaseRenewalAutomationForPropertyManagementCompanies /> },
  { path: "/showing-coordination-automation-for-property-management-companies", element: <ShowingCoordinationAutomationForPropertyManagementCompanies /> },
  { path: "/maintenance-request-automation-for-property-management-companies", element: <MaintenanceRequestAutomationForPropertyManagementCompanies /> },
  { path: "/tenant-onboarding-automation-for-property-management-companies", element: <TenantOnboardingAutomationForPropertyManagementCompanies /> },
  { path: "/tenant-communication-automation-for-property-management-companies", element: <TenantCommunicationAutomationForPropertyManagementCompanies /> },
  { path: "/after-hours-tenant-communication-for-property-management-companies", element: <AfterHoursTenantCommunicationForPropertyManagementCompanies /> },
  { path: "/after-hours-maintenance-triage-for-property-management-companies", element: <AfterHoursMaintenanceTriageForPropertyManagementCompanies /> },
  { path: "/emergency-vs-routine-maintenance-intake-for-property-management-companies", element: <EmergencyVsRoutineMaintenanceIntakeForPropertyManagementCompanies /> },
  { path: "/owner-reporting-automation-for-property-management-companies", element: <OwnerReportingAutomationForPropertyManagementCompanies /> },
  { path: "/ai-automation-ecommerce", element: <AiAutomationEcommerce /> },
  { path: "/what-to-automate-first-for-ecommerce-brands", element: <WhatToAutomateFirstForEcommerceBrands /> },
  { path: "/ai-automation-for-auto-parts-ecommerce", element: <AiAutomationForAutoPartsEcommerce /> },
  { path: "/what-to-automate-first-for-auto-parts-ecommerce", element: <WhatToAutomateFirstForAutoPartsEcommerce /> },
  {
    path: "/crm-automation-vs-manual-follow-up-for-auto-parts-ecommerce",
    element: <CrmAutomationVsManualFollowUpForAutoPartsEcommerce />,
  },
  { path: "/ecommerce-crm-automation-with-ai-follow-up", element: <EcommerceCrmAutomationWithAiFollowUp /> },
  { path: "/ecommerce-crm-automation-vs-manual-follow-up", element: <EcommerceCrmAutomationVsManualFollowUp /> },
  {
    path: "/fitment-inquiry-automation-for-auto-parts-ecommerce",
    element: <FitmentInquiryAutomationForAutoPartsEcommerce />,
  },
  {
    path: "/customer-inquiry-automation-for-auto-parts-ecommerce",
    element: <CustomerInquiryAutomationForAutoPartsEcommerce />,
  },
  {
    path: "/quote-follow-up-automation-for-auto-parts-ecommerce",
    element: <QuoteFollowUpAutomationForAutoPartsEcommerce />,
  },
  {
    path: "/stale-lead-follow-up-for-auto-parts-ecommerce",
    element: <StaleLeadFollowUpForAutoPartsEcommerce />,
  },
  {
    path: "/repeat-purchase-reactivation-automation-for-auto-parts-ecommerce",
    element: <RepeatPurchaseReactivationAutomationForAutoPartsEcommerce />,
  },
  {
    path: "/repeat-purchase-reactivation-automation-for-ecommerce-brands",
    element: <RepeatPurchaseReactivationAutomationForEcommerceBrands />,
  },
  {
    path: "/customer-service-automation-for-ecommerce-brands",
    element: <CustomerServiceAutomationForEcommerceBrands />,
  },
  {
    path: "/customer-service-automation-vs-manual-support-for-ecommerce-brands",
    element: <CustomerServiceAutomationVsManualSupportForEcommerceBrands />,
  },
  {
    path: "/order-status-and-return-support-automation-for-ecommerce-brands",
    element: <OrderStatusAndReturnSupportAutomationForEcommerceBrands />,
  },
  {
    path: "/review-request-automation-for-ecommerce-brands",
    element: <ReviewRequestAutomationForEcommerceBrands />,
  },
  { path: "/after-hours-lead-capture-for-service-businesses", element: <AfterHoursLeadCapture /> },
  { path: "/missed-call-follow-up-automation", element: <MissedCallFollowUp /> },
  { path: "/missed-call-text-back-for-service-businesses", element: <MissedCallTextBackForServiceBusinesses /> },
  { path: "/estimate-follow-up-automation-for-service-businesses", element: <EstimateFollowUpAutomationForServiceBusinesses /> },
  { path: "/estimate-follow-up-vs-quote-follow-up-for-service-businesses", element: <EstimateFollowUpVsQuoteFollowUpForServiceBusinesses /> },
  { path: "/quote-follow-up-automation-for-service-businesses", element: <QuoteFollowUpAutomationForServiceBusinesses /> },
  { path: "/appointment-scheduling-and-reminder-automation-for-service-businesses", element: <AppointmentSchedulingAndReminderAutomationForServiceBusinesses /> },
  { path: "/appointment-scheduling-and-reminder-automation-vs-ai-appointment-setter-for-service-businesses", element: <AppointmentSchedulingAndReminderAutomationVsAiAppointmentSetterForServiceBusinesses /> },
  { path: "/booking-confirmation-and-reminder-automation", element: <BookingConfirmationAndReminder /> },
  { path: "/ai-phone-answering-for-service-businesses", element: <AiPhoneAnswering /> },
  { path: "/missed-call-text-back-vs-ai-phone-answering-for-service-businesses", element: <MissedCallTextBackVsAiPhoneAnsweringForServiceBusinesses /> },
  { path: "/ai-voice-agent-lead-qualification", element: <AiVoiceAgentForLeadQualification /> },
  { path: "/ai-voice-agent-setup-for-lead-qualification", element: <AiVoiceAgentSetupForLeadQualification /> },
  { path: "/ai-voice-agent-setup-cost-small-business", element: <AiVoiceAgentSetupCostSmallBusiness /> },
  { path: "/ai-voice-agent-setup-mistakes-small-business", element: <AiVoiceAgentSetupMistakesSmallBusiness /> },
  { path: "/ai-voice-agent-launch-checklist-small-business", element: <AiVoiceAgentLaunchChecklistSmallBusiness /> },
  { path: "/ai-voice-agent-setup-vs-diy-small-business", element: <AiVoiceAgentSetupVsDiySmallBusiness /> },
  { path: "/ai-voice-agent-cost-small-business", element: <AiVoiceAgentCostSmallBusiness /> },
  { path: "/ai-phone-answering-cost-small-business", element: <AiPhoneAnsweringCostSmallBusiness /> },
  { path: "/ai-phone-answering-setup-small-business", element: <AiPhoneAnsweringSetupSmallBusiness /> },
  { path: "/ai-phone-answering-roi-small-business", element: <AiPhoneAnsweringRoiSmallBusiness /> },
  { path: "/ai-phone-answering-setup-vs-diy-small-business", element: <AiPhoneAnsweringSetupVsDiySmallBusiness /> },
  { path: "/ai-voice-agent-roi-for-lead-follow-up", element: <AiVoiceAgentRoiForLeadFollowUp /> },
  { path: "/instant-lead-response-automation", element: <InstantLeadResponse /> },
  { path: "/contact-form-lead-follow-up-automation", element: <ContactFormLeadFollowUpAutomation /> },
  { path: "/review-request-automation-for-service-businesses", element: <ReviewRequestAutomationForServiceBusinesses /> },
  { path: "/referral-request-automation-for-service-businesses", element: <ReferralRequestAutomationForServiceBusinesses /> },
  { path: "/review-request-vs-referral-request-for-service-businesses", element: <ReviewRequestVsReferralRequestForServiceBusinesses /> },
  {
    path: "/contact-form-autoresponder-vs-full-lead-follow-up",
    element: <ContactFormAutoresponderVsFullLeadFollowUp />,
  },
  { path: "/quote-follow-up-automation", element: <QuoteFollowUp /> },
  { path: "/client-reactivation-automation", element: <ClientReactivation /> },
  { path: "/client-reactivation-automation-for-service-businesses", element: <ClientReactivationAutomationForServiceBusinesses /> },
  { path: "/client-reactivation-cost-small-business", element: <ClientReactivationCostSmallBusiness /> },
  { path: "/client-reactivation-roi-small-business", element: <ClientReactivationRoiSmallBusiness /> },
  { path: "/no-show-reduction-automation", element: <NoShowReduction /> },
  { path: "/ai-appointment-setter-vs-receptionist", element: <AiAppointmentSetterVsReceptionist /> },
  { path: "/ai-appointment-setter-vs-virtual-assistant", element: <AiAppointmentSetterVsVirtualAssistant /> },
  { path: "/ai-voice-agent-vs-voicemail", element: <AiVoiceAgentVsVoicemail /> },
  { path: "/ai-voice-agent-vs-call-center", element: <AiVoiceAgentVsCallCenter /> },
  { path: "/ai-voice-agent-vs-answering-service-for-small-business", element: <AiVoiceAgentVsAnsweringServiceForSmallBusiness /> },
  { path: "/ai-voice-agent-vs-human-appointment-setter", element: <AiVoiceAgentVsHumanAppointmentSetter /> },
  { path: "/ai-voice-agent-vs-manual-callback-for-service-businesses", element: <AiVoiceAgentVsManualCallbackForServiceBusinesses /> },
  { path: "/n8n-vs-make-small-business", element: <N8nVsMakeSmallBusiness /> },
  { path: "/make-vs-zapier-small-business", element: <MakeVsZapierSmallBusiness /> },
  { path: "/build-vs-buy-ai-automation", element: <BuildVsBuyAiAutomation /> },
  { path: "/vapi-vs-retell-small-business", element: <VapiVsRetellSmallBusiness /> },
  { path: "/retell-vs-bland-small-business", element: <RetellVsBlandSmallBusiness /> },
  { path: "/ai-automation-for-chiropractors", element: <AiAutomationForChiropractors /> },
  { path: "/what-to-automate-first-for-chiropractors", element: <WhatToAutomateFirstForChiropractors /> },
  { path: "/care-plan-recall-automation-for-chiropractors", element: <CarePlanRecallAutomationForChiropractors /> },
  { path: "/new-patient-intake-and-scheduling-automation-for-chiropractors", element: <NewPatientIntakeAndSchedulingAutomationForChiropractors /> },
  { path: "/no-show-reduction-automation-for-chiropractors", element: <NoShowReductionAutomationForChiropractors /> },
  { path: "/ai-phone-answering-for-chiropractors", element: <AiPhoneAnsweringForChiropractors /> },
  { path: "/ai-phone-answering-vs-voicemail-for-chiropractors", element: <AiPhoneAnsweringVsVoicemailForChiropractors /> },
  { path: "/missed-call-text-back-vs-ai-phone-answering-for-chiropractors", element: <MissedCallTextBackVsAiPhoneAnsweringForChiropractors /> },
  { path: "/missed-call-text-back-vs-voicemail-for-chiropractors", element: <MissedCallTextBackVsVoicemailForChiropractors /> },
  { path: "/missed-call-text-back-for-chiropractors", element: <MissedCallTextBackForChiropractors /> },
  { path: "/review-request-automation-for-chiropractors", element: <ReviewRequestAutomationForChiropractors /> },
  { path: "/ai-automation-for-cleaning-companies", element: <AiAutomationForCleaningCompanies /> },
  { path: "/what-to-automate-first-for-cleaning-companies", element: <WhatToAutomateFirstForCleaningCompanies /> },
  { path: "/quote-follow-up-automation-for-cleaning-companies", element: <QuoteFollowUpAutomationForCleaningCompanies /> },
  { path: "/recurring-cleaning-scheduling-and-reminder-automation-for-cleaning-companies", element: <RecurringCleaningSchedulingAndReminderAutomationForCleaningCompanies /> },
  { path: "/missed-call-text-back-for-cleaning-companies", element: <MissedCallTextBackForCleaningCompanies /> },
  { path: "/ai-phone-answering-for-cleaning-companies", element: <AiPhoneAnsweringForCleaningCompanies /> },
  { path: "/ai-phone-answering-vs-voicemail-for-cleaning-companies", element: <AiPhoneAnsweringVsVoicemailForCleaningCompanies /> },
  { path: "/missed-call-text-back-vs-ai-phone-answering-for-cleaning-companies", element: <MissedCallTextBackVsAiPhoneAnsweringForCleaningCompanies /> },
  { path: "/missed-call-text-back-vs-voicemail-for-cleaning-companies", element: <MissedCallTextBackVsVoicemailForCleaningCompanies /> },
  { path: "/client-reactivation-automation-for-cleaning-companies", element: <ClientReactivationAutomationForCleaningCompanies /> },
  { path: "/review-request-automation-for-cleaning-companies", element: <ReviewRequestAutomationForCleaningCompanies /> },
  { path: "/ai-lead-follow-up-for-cleaning-companies", element: <AiLeadFollowUpForCleaningCompanies /> },
  { path: "/ai-automation-for-med-spas", element: <AiAutomationForMedSpas /> },
  { path: "/what-to-automate-first-for-med-spas", element: <WhatToAutomateFirstForMedSpas /> },
  { path: "/missed-call-text-back-for-med-spas", element: <MissedCallTextBackForMedSpas /> },
  { path: "/missed-call-text-back-vs-voicemail-for-med-spas", element: <MissedCallTextBackVsVoicemailForMedSpas /> },
  { path: "/missed-call-text-back-vs-ai-phone-answering-for-med-spas", element: <MissedCallTextBackVsAiPhoneAnsweringForMedSpas /> },
  { path: "/ai-phone-answering-for-med-spas", element: <AiPhoneAnsweringForMedSpas /> },
  { path: "/ai-phone-answering-vs-voicemail-for-med-spas", element: <AiPhoneAnsweringVsVoicemailForMedSpas /> },
  { path: "/consultation-booking-and-reminder-automation-for-med-spas", element: <ConsultationBookingAndReminderAutomationForMedSpas /> },
  { path: "/no-show-reduction-automation-for-med-spas", element: <NoShowReductionAutomationForMedSpas /> },
  { path: "/treatment-recall-automation-for-med-spas", element: <TreatmentRecallAutomationForMedSpas /> },
  { path: "/review-request-automation-for-med-spas", element: <ReviewRequestAutomationForMedSpas /> },
  { path: "/ai-lead-follow-up-for-med-spas", element: <AiLeadFollowUpForMedSpas /> },
  { path: "/ai-automation-for-roofing-companies", element: <AiAutomationForRoofingCompanies /> },
  { path: "/what-to-automate-first-for-roofing-companies", element: <WhatToAutomateFirstForRoofingCompanies /> },
  { path: "/ai-lead-follow-up-for-roofing-companies", element: <AiLeadFollowUpForRoofingCompanies /> },
  { path: "/insurance-claim-follow-up-for-roofing-companies", element: <InsuranceClaimFollowUpForRoofingCompanies /> },
  { path: "/client-reactivation-automation-for-roofing-companies", element: <ClientReactivationAutomationForRoofingCompanies /> },
  { path: "/missed-call-text-back-for-roofing-companies", element: <MissedCallTextBackForRoofingCompanies /> },
  { path: "/missed-call-text-back-vs-ai-phone-answering-for-roofing-companies", element: <MissedCallTextBackVsAiPhoneAnsweringForRoofingCompanies /> },
  { path: "/missed-call-text-back-vs-voicemail-for-roofing-companies", element: <MissedCallTextBackVsVoicemailForRoofingCompanies /> },
  { path: "/ai-phone-answering-for-roofing-companies", element: <AiPhoneAnsweringForRoofingCompanies /> },
  { path: "/ai-phone-answering-vs-voicemail-for-roofing-companies", element: <AiPhoneAnsweringVsVoicemailForRoofingCompanies /> },
  { path: "/review-request-automation-for-roofing-companies", element: <ReviewRequestAutomationForRoofingCompanies /> },
  { path: "/ai-automation-for-pest-control-companies", element: <AiAutomationForPestControlCompanies /> },
  { path: "/ai-automation-for-pool-service-companies", element: <AiAutomationForPoolServiceCompanies /> },
  { path: "/what-to-automate-first-for-pool-service-companies", element: <WhatToAutomateFirstForPoolServiceCompanies /> },
  { path: "/ai-lead-follow-up-for-pool-service-companies", element: <AiLeadFollowUpForPoolServiceCompanies /> },
  { path: "/quote-follow-up-automation-for-pool-service-companies", element: <QuoteFollowUpAutomationForPoolServiceCompanies /> },
  { path: "/recurring-service-reminder-automation-for-pool-service-companies", element: <RecurringServiceReminderAutomationForPoolServiceCompanies /> },
  { path: "/seasonal-opening-and-closing-outreach-for-pool-service-companies", element: <SeasonalOpeningAndClosingOutreachForPoolServiceCompanies /> },
  { path: "/review-request-automation-for-pool-service-companies", element: <ReviewRequestAutomationForPoolServiceCompanies /> },
  { path: "/missed-call-text-back-for-pool-service-companies", element: <MissedCallTextBackForPoolServiceCompanies /> },
  { path: "/missed-call-text-back-vs-voicemail-for-pool-service-companies", element: <MissedCallTextBackVsVoicemailForPoolServiceCompanies /> },
  { path: "/ai-phone-answering-for-pool-service-companies", element: <AiPhoneAnsweringForPoolServiceCompanies /> },
  { path: "/ai-phone-answering-vs-voicemail-for-pool-service-companies", element: <AiPhoneAnsweringVsVoicemailForPoolServiceCompanies /> },
  { path: "/missed-call-text-back-vs-ai-phone-answering-for-pool-service-companies", element: <MissedCallTextBackVsAiPhoneAnsweringForPoolServiceCompanies /> },
  { path: "/what-to-automate-first-for-pest-control-companies", element: <WhatToAutomateFirstForPestControlCompanies /> },
  { path: "/recurring-service-reminder-automation-for-pest-control-companies", element: <RecurringServiceReminderAutomationForPestControlCompanies /> },
  { path: "/seasonal-campaign-automation-for-pest-control-companies", element: <SeasonalCampaignAutomationForPestControlCompanies /> },
  { path: "/urgent-lead-follow-up-for-pest-control-companies", element: <UrgentLeadFollowUpForPestControlCompanies /> },
  { path: "/ai-lead-follow-up-for-pest-control-companies", element: <AiLeadFollowUpForPestControlCompanies /> },
  { path: "/quote-follow-up-automation-for-pest-control-companies", element: <QuoteFollowUpAutomationForPestControlCompanies /> },
  { path: "/review-request-automation-for-pest-control-companies", element: <ReviewRequestAutomationForPestControlCompanies /> },
  { path: "/ai-phone-answering-for-pest-control-companies", element: <AiPhoneAnsweringForPestControlCompanies /> },
  { path: "/missed-call-text-back-for-pest-control-companies", element: <MissedCallTextBackForPestControlCompanies /> },
  { path: "/missed-call-text-back-vs-voicemail-for-pest-control-companies", element: <MissedCallTextBackVsVoicemailForPestControlCompanies /> },
  { path: "/missed-call-text-back-vs-ai-phone-answering-for-pest-control-companies", element: <MissedCallTextBackVsAiPhoneAnsweringForPestControlCompanies /> },
  { path: "/ai-phone-answering-vs-voicemail-for-pest-control-companies", element: <AiPhoneAnsweringVsVoicemailForPestControlCompanies /> },
  { path: "/ai-automation-for-auto-repair-shops", element: <AiAutomationForAutoRepairShops /> },
  { path: "/what-to-automate-first-for-auto-repair-shops", element: <WhatToAutomateFirstForAutoRepairShops /> },
  { path: "/ai-lead-follow-up-for-auto-repair-shops", element: <AiLeadFollowUpForAutoRepairShops /> },
  { path: "/maintenance-reminder-automation-for-auto-repair-shops", element: <MaintenanceReminderAutomationForAutoRepairShops /> },
  { path: "/client-reactivation-automation-for-auto-repair-shops", element: <ClientReactivationAutomationForAutoRepairShops /> },
  { path: "/estimate-follow-up-automation-for-auto-repair-shops", element: <EstimateFollowUpAutomationForAutoRepairShops /> },
  { path: "/appointment-scheduling-and-reminder-automation-for-auto-repair-shops", element: <AppointmentSchedulingAndReminderAutomationForAutoRepairShops /> },
  { path: "/missed-call-text-back-for-auto-repair-shops", element: <MissedCallTextBackForAutoRepairShops /> },
  { path: "/missed-call-text-back-vs-voicemail-for-auto-repair-shops", element: <MissedCallTextBackVsVoicemailForAutoRepairShops /> },
  { path: "/missed-call-text-back-vs-ai-phone-answering-for-auto-repair-shops", element: <MissedCallTextBackVsAiPhoneAnsweringForAutoRepairShops /> },
  { path: "/ai-phone-answering-for-auto-repair-shops", element: <AiPhoneAnsweringForAutoRepairShops /> },
  { path: "/ai-phone-answering-vs-voicemail-for-auto-repair-shops", element: <AiPhoneAnsweringVsVoicemailForAutoRepairShops /> },
  { path: "/review-request-automation-for-auto-repair-shops", element: <ReviewRequestAutomationForAutoRepairShops /> },
  { path: "/ai-automation-for-landscaping-companies", element: <AiAutomationForLandscapingCompanies /> },
  { path: "/what-to-automate-first-for-landscaping-companies", element: <WhatToAutomateFirstForLandscapingCompanies /> },
  { path: "/ai-lead-follow-up-for-landscaping-companies", element: <AiLeadFollowUpForLandscapingCompanies /> },
  { path: "/missed-call-text-back-for-landscaping-companies", element: <MissedCallTextBackForLandscapingCompanies /> },
  { path: "/missed-call-text-back-vs-voicemail-for-landscaping-companies", element: <MissedCallTextBackVsVoicemailForLandscapingCompanies /> },
  { path: "/missed-call-text-back-vs-ai-phone-answering-for-landscaping-companies", element: <MissedCallTextBackVsAiPhoneAnsweringForLandscapingCompanies /> },
  { path: "/estimate-follow-up-automation-for-landscaping-companies", element: <EstimateFollowUpAutomationForLandscapingCompanies /> },
  { path: "/review-request-automation-for-landscaping-companies", element: <ReviewRequestAutomationForLandscapingCompanies /> },
  { path: "/recurring-service-scheduling-and-reminder-automation-for-landscaping-companies", element: <RecurringServiceSchedulingAndReminderAutomationForLandscapingCompanies /> },
  { path: "/ai-phone-answering-for-landscaping-companies", element: <AiPhoneAnsweringForLandscapingCompanies /> },
  { path: "/ai-phone-answering-vs-voicemail-for-landscaping-companies", element: <AiPhoneAnsweringVsVoicemailForLandscapingCompanies /> },
  { path: "/seasonal-reactivation-automation-for-landscaping-companies", element: <SeasonalReactivationAutomationForLandscapingCompanies /> },
  { path: "/ai-automation-for-painting-contractors", element: <AiAutomationForPaintingContractors /> },
  { path: "/ai-lead-follow-up-for-painting-contractors", element: <AiLeadFollowUpForPaintingContractors /> },
  { path: "/client-reactivation-automation-for-painting-contractors", element: <ClientReactivationAutomationForPaintingContractors /> },
  { path: "/estimate-follow-up-automation-for-painting-contractors", element: <EstimateFollowUpAutomationForPaintingContractors /> },
  { path: "/what-to-automate-first-for-painting-contractors", element: <WhatToAutomateFirstForPaintingContractors /> },
  { path: "/missed-call-text-back-for-painting-contractors", element: <MissedCallTextBackForPaintingContractors /> },
  { path: "/missed-call-text-back-vs-voicemail-for-painting-contractors", element: <MissedCallTextBackVsVoicemailForPaintingContractors /> },
  { path: "/ai-phone-answering-for-painting-contractors", element: <AiPhoneAnsweringForPaintingContractors /> },
  { path: "/ai-phone-answering-vs-voicemail-for-painting-contractors", element: <AiPhoneAnsweringVsVoicemailForPaintingContractors /> },
  { path: "/missed-call-text-back-vs-ai-phone-answering-for-painting-contractors", element: <MissedCallTextBackVsAiPhoneAnsweringForPaintingContractors /> },
  { path: "/review-request-automation-for-painting-contractors", element: <ReviewRequestAutomationForPaintingContractors /> },
  { path: "/referral-request-automation-for-painting-contractors", element: <ReferralRequestAutomationForPaintingContractors /> },
  { path: "/ai-automation-for-home-inspectors", element: <AiAutomationForHomeInspectors /> },
  { path: "/what-to-automate-first-for-home-inspectors", element: <WhatToAutomateFirstForHomeInspectors /> },
  { path: "/ai-lead-follow-up-for-home-inspectors", element: <AiLeadFollowUpForHomeInspectors /> },
  {
    path: "/inspection-scheduling-and-reminder-automation-for-home-inspectors",
    element: <InspectionSchedulingAndReminderAutomationForHomeInspectors />,
  },
  {
    path: "/report-delivery-and-review-automation-for-home-inspectors",
    element: <ReportDeliveryAndReviewAutomationForHomeInspectors />,
  },
  {
    path: "/review-request-automation-for-home-inspectors",
    element: <ReviewRequestAutomationForHomeInspectors />,
  },
  {
    path: "/real-estate-agent-nurture-for-home-inspectors",
    element: <RealEstateAgentNurtureForHomeInspectors />,
  },
  { path: "/ai-phone-answering-for-home-inspectors", element: <AiPhoneAnsweringForHomeInspectors /> },
  { path: "/ai-phone-answering-vs-voicemail-for-home-inspectors", element: <AiPhoneAnsweringVsVoicemailForHomeInspectors /> },
  { path: "/missed-call-text-back-for-home-inspectors", element: <MissedCallTextBackForHomeInspectors /> },
  { path: "/missed-call-text-back-vs-voicemail-for-home-inspectors", element: <MissedCallTextBackVsVoicemailForHomeInspectors /> },
  { path: "/missed-call-text-back-vs-ai-phone-answering-for-home-inspectors", element: <MissedCallTextBackVsAiPhoneAnsweringForHomeInspectors /> },
  { path: "/ai-automation-cost-small-business", element: <AiAutomationCostSmallBusiness /> },
  { path: "/ai-automation-time-savings-small-business", element: <AiAutomationTimeSavingsSmallBusiness /> },
  { path: "/ai-automation-maintenance-and-support-small-business", element: <AiAutomationMaintenanceAndSupportSmallBusiness /> },
  { path: "/affordable-ai-automation-small-business", element: <AffordableAiAutomationSmallBusiness /> },
  { path: "/ai-automation-audit-checklist", element: <AiAutomationAuditChecklist /> },
  { path: "/crm-automation-examples-small-business", element: <CrmAutomationExamplesSmallBusiness /> },
  { path: "/crm-automation-for-contractors", element: <CrmAutomationForContractors /> },
  { path: "/crm-pipeline-stages-for-contractors", element: <CrmPipelineStagesForContractors /> },
  { path: "/crm-automation-setup-for-contractors", element: <CrmAutomationSetupForContractors /> },
  { path: "/what-to-automate-first-for-contractors", element: <WhatToAutomateFirstForContractors /> },
  { path: "/crm-automation-setup-cost-for-contractors", element: <CrmAutomationSetupCostForContractors /> },
  { path: "/crm-automation-setup-vs-diy-for-contractors", element: <CrmAutomationSetupVsDiyForContractors /> },
  { path: "/estimate-follow-up-automation-for-contractors", element: <EstimateFollowUpAutomationForContractors /> },
  { path: "/estimate-follow-up-automation-for-roofing-companies", element: <EstimateFollowUpAutomationForRoofingCompanies /> },
  { path: "/roofing-scheduling-and-follow-up-automation", element: <RoofingSchedulingAndFollowUpAutomation /> },
  { path: "/dispatch-handoff-automation-for-contractors", element: <DispatchHandoffAutomationForContractors /> },
  { path: "/job-intake-routing-automation-for-contractors", element: <JobIntakeRoutingAutomationForContractors /> },
  { path: "/lead-follow-up-automation-examples", element: <LeadFollowUpAutomationExamples /> },
  { path: "/ai-automation-implementation-roadmap", element: <AiAutomationImplementationRoadmap /> },
  { path: "/ai-automation-integrations-small-business", element: <AiAutomationIntegrationsSmallBusiness /> },
  { path: "/what-processes-can-ai-automate-in-my-business", element: <WhatProcessesCanAiAutomateInMyBusiness /> },
  { path: "/privacy", element: <PrivacyPolicy /> },
  { path: "/terms", element: <TermsOfService /> },
  { path: "*", element: <NotFound />, prerender: false },
];

export const prerenderRoutes = appRoutes
  .filter((route) => route.prerender !== false)
  .map((route) => route.path);
